<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Erola Fenollosa">

<title>Analysing proportions - Seed germination</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Rewild or Wait - analysing proportions_files/libs/clipboard/clipboard.min.js"></script>
<script src="Rewild or Wait - analysing proportions_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="Rewild or Wait - analysing proportions_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="Rewild or Wait - analysing proportions_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="Rewild or Wait - analysing proportions_files/libs/quarto-html/popper.min.js"></script>
<script src="Rewild or Wait - analysing proportions_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Rewild or Wait - analysing proportions_files/libs/quarto-html/anchor.min.js"></script>
<link href="Rewild or Wait - analysing proportions_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Rewild or Wait - analysing proportions_files/libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Rewild or Wait - analysing proportions_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Rewild or Wait - analysing proportions_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Rewild or Wait - analysing proportions_files/libs/bootstrap/bootstrap-9e3ffae467580fdb927a41352e75a2e0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Analysing proportions - Seed germination</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Erola Fenollosa </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="rewild-or-wait-should-we-reintroduce-the-alpine-forget-me-not-this-year" class="level1">
<h1>Rewild or Wait? Should we reintroduce the Alpine Forget-me-not this year?</h1>
</section>
<section id="overview-of-this-practical" class="level1">
<h1>0. Overview of this practical</h1>
<p>In this practical you will:</p>
<ul>
<li><p>Act as the <strong>Alpine Rewilding Task Force</strong>, using statistical evidence to decide whether to reintroduce <em>Eritrichium nanum</em>.</p></li>
<li><p>Analyse <strong>proportion data</strong> using the binomial model (success/failure) and recognise when count data should instead follow a <strong>Poisson model</strong>.</p></li>
<li><p>Estimate germination rates using the <strong>binomial test</strong> and <strong>Agresti–Coull confidence intervals</strong>, and interpret what these say about management thresholds.</p></li>
<li><p>Compare treatments using <strong>chi-square and Fisher’s exact tests</strong>, and apply <strong>goodness-of-fit tests</strong> (χ² and G-test) to assess whether observed counts match expectations.</p></li>
<li><p><strong>Critically evaluate statistical assumptions</strong> (independence, expected counts, overdispersion) and link uncertainty to real conservation decisions.</p></li>
</ul>
<p><strong>IMPORTANT: Today aim is not to learn how to code this, but to understand the numbers. You will <em>not be asked to edit any of the code</em> provided.</strong></p>
</section>
<section id="context-of-the-data" class="level1">
<h1>1. Context of the data</h1>
<p>The rare alpine flower Forget-me-not (<em>Eritrichium nanum</em>) has disappeared two years ago from our regional mountain range due to warming and reduced snowpack. The seed bank holds 5,000 viable seeds collected before local extinction. You are the Alpine Restoration Committee and you need to make a decision: Should we attempt reintroduction this year?</p>
<p>Unfortunately, funds are limited and you can’t recommend reintroduction unless you are certain that it can be successful, not only due to the limited funding but also due to the limited amount of seeds (i.e.&nbsp;you have only one opportunity to reintroduce).</p>
<p>Specifically, the conservation fund will support a reintroduction <strong>only if estimated germination proportion ≥ 0.40</strong>. Additionally, the Board requires that we be reasonably certain that true germination is not below 0.30 (they asked for about 95% confidence that true p &gt; 0.30). Seeds have been stored in optimal conditions for preservation, and eventhough some seed ageing might happen (i.e.&nbsp;seeds will be less likely to remain viable with storage time), scientific evidence from similar species reveal that specific treatments can contribute to break seed dormancy.</p>
<p><em>PAUSE: In case you are not familiar with artificial seed banks and seed dormancy, just a quick non-scientific language note: Seeds from some species can go dormant, meaning they will wait for germination until they receive certain environmental cues (increase in the number of light hours or increase of temperature, meaning spring is coming, as well as low temperatures for a certain period might indicate winter is over, or even “feeling” an acidic environment means seeds have gone through the digestive system of an animal and have been dispersed far enough from the mother, this is called scarification). In artificial seed banks, researchers explore the optimal conditions to preserve seeds in a dormant state (each species have evolved to respond to different environmental cues), as well as the optimal conditions to “wake all seeds up”, maintaining high viability. Plants have evolved to not always germinate 100% for different reasons, including a bed-hedging strategy. Natural germination rates could range from 20 to 80%. This would mean, that if 30% germination is expected, every time we want to get some plants from the seed bank, we will be wasting 70% of the preserved sample. For this reason, unraveling which conditions are required for optimal germination is essential in seed bank management.</em></p>
<p>Let’s get back to the case. For the alpine flower Forget-me-not, you have started small pilot trials to compare two “seed awakening” (dormancy break) treatments:</p>
<ul>
<li><p><code>Cold</code> treatment (current protocol). This method mimics natural alpine winter conditions. Seeds are stored at 4 degrees for 8 weeks. The cold period simulates snow cover and winter chilling. It is cheap and logistically simple, requiring only refrigeration space.</p></li>
<li><p><code>Warm</code> treatment (experimental). This method simulates early spring soil warming. Seeds are first hydrated and then exposed to controlled warm temperatures (day: 15 degrees, night, 5 degrees) for 10 weeks. Some alpine seeds respond strongly to temperature fluctuations.</p></li>
</ul>
<p>For each treatment you use 12 petri dishes (or trays), 25 seeds per petri dishes. <strong>Your job is to analyse the pilot data, quantify uncertainty, and recommend Proceed or Delay.</strong></p>
<p><strong>The rules:</strong></p>
<ul>
<li><p>Snowpack conditions are ideal this year</p></li>
<li><p>Funding is limited</p></li>
<li><p>You have one opportunity to reintroduce</p></li>
</ul>
<p><strong>Management rules (given):</strong></p>
<ul>
<li><p><strong>Proceed</strong> with reintroduction if estimated germination proportion <code>p_hat ≥ 0.40</code> <strong>and</strong> you are confident the true p is not below 0.30 (the Board wants ~95% confidence p &gt; 0.30).</p></li>
<li><p><strong>Delay</strong>. If results are borderline, discuss risk and recommend more trials or a pilot field test.</p></li>
</ul>
<p><strong>Risk Matrix (use this to decide):</strong></p>
<ul>
<li><p><strong>Green (Proceed):</strong> lower bound of 95% CI &gt; 0.40 → proceed.</p></li>
<li><p><strong>Amber (Caution / Conditional Proceed):</strong> 95% CI includes 0.40 but lower bound &gt; 0.30 → risky but consider limited pilot reintroductions or more replication.</p></li>
<li><p><strong>Red (Delay):</strong> upper bound of 95% CI &lt; 0.40 OR lower bound ≤ 0.30 → do not proceed; collect more data or improve protocol.</p></li>
</ul>
<p><img src="http://science.halleyhosting.com/nature/denali/flora/5/borage/eritrichium/nanum/aretioides3c.jpg" class="img-fluid" width="262"></p>
<p><img src="http://science.halleyhosting.com/nature/denali/flora/5/borage/eritrichium/nanum/aretioides3f.jpg" class="img-fluid" width="289"></p>
<p><img src="https://seedidguide.idseed.org/wp-content/uploads/2021/06/5dc087bbdacc3.jpg" class="img-fluid" width="295"></p>
<p>Information about the species here: <a href="https://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:907822-1" class="uri">https://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:907822-1</a></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Minimal package installs (run once)</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">requireNamespace</span>(<span class="st">"binom"</span>, <span class="at">quietly =</span> <span class="cn">TRUE</span>)) <span class="fu">install.packages</span>(<span class="st">"binom"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(binom)      <span class="co"># Agresti–Coull CIs</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'binom' was built under R version 4.5.2</code></pre>
</div>
</div>
</section>
<section id="prediction-game-make-your-bets" class="level1">
<h1>2. Prediction game — make your bets</h1>
<p><strong>QUESTION 1.</strong> For each treatment (<code>Cold</code>, <code>Warm</code>) write a predicted germination proportion <code>p_hat</code> between 0 and 1. Example: Cold = 0.45, Warm = 0.70. For each prediction, write one sentence biological justification. Assign a confidence level (low, medium, high) meaning your chance of being within ±0.10 of the true p: low ≈ 30% chance, medium ≈ 60% chance, high ≈ 90% chance.</p>
<p>ANSWER:</p>
<p><sub><strong>Possible&nbsp;answer:</strong>&nbsp;Predictions&nbsp;should&nbsp;combine&nbsp;biological&nbsp;reasoning&nbsp;and&nbsp;explicit&nbsp;uncertainty.&nbsp;In&nbsp;this&nbsp;case&nbsp;we&nbsp;have&nbsp;very&nbsp;limited&nbsp;information,&nbsp;so&nbsp;this&nbsp;is&nbsp;based&nbsp;on&nbsp;your&nbsp;imagination.&nbsp;A&nbsp;reasonable&nbsp;prediction&nbsp;would&nbsp;be&nbsp;Cold&nbsp;≈&nbsp;0.60&nbsp;and&nbsp;Warm&nbsp;≈&nbsp;0.70.&nbsp;Cold&nbsp;stratification&nbsp;mimics&nbsp;natural&nbsp;alpine&nbsp;winter&nbsp;conditions,&nbsp;so&nbsp;we&nbsp;expect&nbsp;moderate-high&nbsp;germination&nbsp;around&nbsp;60%,&nbsp;while&nbsp;the&nbsp;Warm&nbsp;treatment&nbsp;may&nbsp;enhance&nbsp;dormancy&nbsp;break&nbsp;and&nbsp;increase&nbsp;germination&nbsp;by&nbsp;roughly&nbsp;10&nbsp;percentage&nbsp;points.&nbsp;I&nbsp;would&nbsp;assign&nbsp;medium&nbsp;confidence&nbsp;(≈60%&nbsp;chance&nbsp;of&nbsp;being&nbsp;within&nbsp;±0.10&nbsp;of&nbsp;the&nbsp;true&nbsp;value),&nbsp;since&nbsp;although&nbsp;there&nbsp;is&nbsp;biological&nbsp;justification&nbsp;for&nbsp;Warm&nbsp;performing&nbsp;better,&nbsp;pilot&nbsp;conditions&nbsp;may&nbsp;not&nbsp;perfectly&nbsp;reflect&nbsp;field&nbsp;responses&nbsp;and&nbsp;seed&nbsp;dormancy&nbsp;can&nbsp;be&nbsp;variable.&nbsp;Getting&nbsp;used&nbsp;to&nbsp;generate&nbsp;expectations&nbsp;is&nbsp;key&nbsp;in&nbsp;statistics,&nbsp;I&nbsp;would&nbsp;recomend&nbsp;to&nbsp;do&nbsp;it&nbsp;as&nbsp;a&nbsp;habit.</sub></p>
</section>
<section id="load-the-data" class="level1">
<h1>3. Load the data</h1>
<p>These are the results of your pilot trial (12 petri dishes per treatment, 25 seeds each):</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>) </span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">tray =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">24</span>,   <span class="at">treatment =</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"Cold"</span>,<span class="st">"Warm"</span>), <span class="at">each =</span> <span class="dv">12</span>),   <span class="at">n_seeds =</span> <span class="fu">rep</span>(<span class="dv">25</span>, <span class="dv">24</span>) )  </span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulate realistic pilot results: Cold ~ 0.40, Warm ~ 0.50 </span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>n_germinated <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">rbinom</span>(<span class="dv">12</span>, <span class="at">size =</span> <span class="dv">25</span>, <span class="at">prob =</span> <span class="fl">0.40</span>),                     </span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="fu">rbinom</span>(<span class="dv">12</span>, <span class="at">size =</span> <span class="dv">25</span>, <span class="at">prob =</span> <span class="fl">0.50</span>))  </span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Show first rows </span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df, <span class="dv">6</span>) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  tray treatment n_seeds n_germinated
1    1      Cold      25           13
2    2      Cold      25           14
3    3      Cold      25            9
4    4      Cold      25           12
5    5      Cold      25           11
6    6      Cold      25           10</code></pre>
</div>
</div>
<p><img src="https://www.cambridge.org/core/blog/wp-content/uploads/2022/07/Onofri3.jpg" class="img-fluid"></p>
</section>
<section id="reveal-the-numbers" class="level1">
<h1>4. Reveal the numbers</h1>
<p>A first thing we want to do is calculate the germination percentages and contrast your prior predictions. With the code below you can aggregate the data by treatment and show proportions:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>tray <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">24</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>treatment <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"Cold"</span>,<span class="st">"Warm"</span>), <span class="at">each =</span> <span class="dv">12</span>)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>n_seeds <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">25</span>, <span class="dv">24</span>)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulate pilot results: Cold ~ 0.40, Warm ~ 0.50</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>n_germinated <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">rbinom</span>(<span class="dv">12</span>, <span class="at">size =</span> <span class="dv">25</span>, <span class="at">prob =</span> <span class="fl">0.40</span>),</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>                  <span class="fu">rbinom</span>(<span class="dv">12</span>, <span class="at">size =</span> <span class="dv">25</span>, <span class="at">prob =</span> <span class="fl">0.50</span>))</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">tray =</span> tray,</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>                 <span class="at">treatment =</span> treatment,</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>                 <span class="at">n_seeds =</span> n_seeds,</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>                 <span class="at">n_germinated =</span> n_germinated,</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>                 <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a><span class="co"># show first rows</span></span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  tray treatment n_seeds n_germinated
1    1      Cold      25           13
2    2      Cold      25           14
3    3      Cold      25            9
4    4      Cold      25           12
5    5      Cold      25           11
6    6      Cold      25           10</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ---- Simple observed summary by treatment (base R) ----</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>total_germ <span class="ot">&lt;-</span> <span class="fu">tapply</span>(df<span class="sc">$</span>n_germinated, df<span class="sc">$</span>treatment, sum)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>total_seeds <span class="ot">&lt;-</span> <span class="fu">tapply</span>(df<span class="sc">$</span>n_seeds, df<span class="sc">$</span>treatment, sum)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>p_hat <span class="ot">&lt;-</span> total_germ <span class="sc">/</span> total_seeds</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>trays <span class="ot">&lt;-</span> <span class="fu">tapply</span>(df<span class="sc">$</span>n_germinated, df<span class="sc">$</span>treatment, length)</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>summary_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">treatment =</span> <span class="fu">names</span>(total_germ),</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">total_germ =</span> <span class="fu">as.integer</span>(total_germ),</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">total_seeds =</span> <span class="fu">as.integer</span>(total_seeds),</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">p_hat =</span> <span class="fu">as.numeric</span>(p_hat),</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">trays =</span> <span class="fu">as.integer</span>(trays),</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">row.names =</span> <span class="cn">NULL</span>,</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span></span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(summary_df)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  treatment total_germ total_seeds     p_hat trays
1      Cold        131         300 0.4366667    12
2      Warm        168         300 0.5600000    12</code></pre>
</div>
</div>
<p><strong>QUESTION:</strong> Were your guesses close to the actual germination rates? Are the results surprising? Would you say there is evidence to prove that one of the treatments work better than the other when germinating the Forget-me-not seeds? Consider if you think we have used enough, or more than enough seeds to do this test.</p>
<p><em>ANSWER</em>:</p>
<p><sub><strong>Possible&nbsp;answer:</strong>&nbsp;According&nbsp;to&nbsp;the&nbsp;numbers,&nbsp;the&nbsp;total&nbsp;seeds&nbsp;that&nbsp;germinated&nbsp;in&nbsp;the&nbsp;cold&nbsp;treatment&nbsp;were&nbsp;131&nbsp;out&nbsp;of&nbsp;300,&nbsp;which&nbsp;is&nbsp;a&nbsp;proportion&nbsp;of&nbsp;0.45&nbsp;(p&nbsp;hat).&nbsp;The&nbsp;warm&nbsp;had&nbsp;a&nbsp;higher&nbsp;germination&nbsp;percentage,&nbsp;with&nbsp;p&nbsp;hat&nbsp;being&nbsp;0.56,&nbsp;which&nbsp;is&nbsp;a&nbsp;56%&nbsp;of&nbsp;germination.&nbsp;I&nbsp;am&nbsp;surprised&nbsp;by&nbsp;the&nbsp;low&nbsp;germinations&nbsp;percentages&nbsp;found.&nbsp;I&nbsp;can’t&nbsp;be&nbsp;sure&nbsp;if&nbsp;the&nbsp;treatments&nbsp;are&nbsp;different,&nbsp;but&nbsp;they&nbsp;seem&nbsp;to&nbsp;have&nbsp;both&nbsp;medium&nbsp;to&nbsp;low&nbsp;germination&nbsp;percentages.&nbsp;The&nbsp;estimated&nbsp;proportion&nbsp;of&nbsp;seeds&nbsp;that&nbsp;germinated&nbsp;was&nbsp;lower&nbsp;in&nbsp;the&nbsp;cold&nbsp;treatment,&nbsp;but&nbsp;I&nbsp;need&nbsp;to&nbsp;understand&nbsp;the&nbsp;variability&nbsp;of&nbsp;this&nbsp;p&nbsp;hat&nbsp;to&nbsp;guarantee&nbsp;if&nbsp;there&nbsp;are&nbsp;differences&nbsp;or&nbsp;not.&nbsp;The&nbsp;total&nbsp;number&nbsp;of&nbsp;seeds&nbsp;seem&nbsp;high,&nbsp;but&nbsp;since&nbsp;less&nbsp;than&nbsp;half&nbsp;germinated,&nbsp;perhaps&nbsp;it&nbsp;was&nbsp;a&nbsp;good&nbsp;idea&nbsp;to&nbsp;have&nbsp;that&nbsp;many.</sub></p>
</section>
<section id="visualise-data-look-before-you-test" class="level1">
<h1>5. Visualise data — look before you test</h1>
<p>Plot tray-level proportions and overlay group means. Compute Agresti–Coull CI</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># colours consistent with your ggplot version </span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>col_cold <span class="ot">&lt;-</span> <span class="st">"#2C7BB6"</span> </span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>col_warm <span class="ot">&lt;-</span> <span class="st">"#D7191C"</span> </span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>cols <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(df<span class="sc">$</span>treatment <span class="sc">==</span> <span class="st">"Cold"</span>, col_cold, col_warm) </span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="co"># per-tray proportions </span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>prop_per_tray <span class="ot">&lt;-</span> df<span class="sc">$</span>n_germinated <span class="sc">/</span> df<span class="sc">$</span>n_seeds</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Set margins</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">5</span>,<span class="dv">5</span>,<span class="dv">4</span>,<span class="dv">2</span>) <span class="sc">+</span> <span class="fl">0.1</span>)</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Split proportions by treatment</span></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>prop_cold <span class="ot">&lt;-</span> prop_per_tray[df<span class="sc">$</span>treatment <span class="sc">==</span> <span class="st">"Cold"</span>]</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>prop_warm <span class="ot">&lt;-</span> prop_per_tray[df<span class="sc">$</span>treatment <span class="sc">==</span> <span class="st">"Warm"</span>]</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot empty frame first</span></span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="dv">1</span>, <span class="at">type =</span> <span class="st">"n"</span>,</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlim =</span> <span class="fu">c</span>(<span class="fl">0.5</span>, <span class="fl">2.5</span>), <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>),</span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>     <span class="at">xaxt =</span> <span class="st">"n"</span>,</span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Treatment"</span>,</span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Germination proportion per tray"</span>,</span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Per-petri dish germination proportions of Eritrichium nanum"</span>)</span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="dv">1</span>, <span class="at">at =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Cold"</span>,<span class="st">"Warm"</span>))</span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-25"><a href="#cb9-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Add jittered points manually</span></span>
<span id="cb9-26"><a href="#cb9-26" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(<span class="fu">jitter</span>(<span class="fu">rep</span>(<span class="dv">1</span>, <span class="fu">length</span>(prop_cold)), <span class="at">amount =</span> <span class="fl">0.08</span>),</span>
<span id="cb9-27"><a href="#cb9-27" aria-hidden="true" tabindex="-1"></a>       prop_cold, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">col =</span> col_cold)</span>
<span id="cb9-28"><a href="#cb9-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-29"><a href="#cb9-29" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(<span class="fu">jitter</span>(<span class="fu">rep</span>(<span class="dv">2</span>, <span class="fu">length</span>(prop_warm)), <span class="at">amount =</span> <span class="fl">0.08</span>),</span>
<span id="cb9-30"><a href="#cb9-30" aria-hidden="true" tabindex="-1"></a>       prop_warm, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">col =</span> col_warm)</span>
<span id="cb9-31"><a href="#cb9-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-32"><a href="#cb9-32" aria-hidden="true" tabindex="-1"></a><span class="co"># Overlay group means</span></span>
<span id="cb9-33"><a href="#cb9-33" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(<span class="dv">1</span>, <span class="fu">mean</span>(prop_cold), <span class="at">pch =</span> <span class="dv">18</span>, <span class="at">cex =</span> <span class="fl">2.2</span>)</span>
<span id="cb9-34"><a href="#cb9-34" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(<span class="dv">2</span>, <span class="fu">mean</span>(prop_warm), <span class="at">pch =</span> <span class="dv">18</span>, <span class="at">cex =</span> <span class="fl">2.2</span>)</span>
<span id="cb9-35"><a href="#cb9-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-36"><a href="#cb9-36" aria-hidden="true" tabindex="-1"></a><span class="co"># Add legend</span></span>
<span id="cb9-37"><a href="#cb9-37" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"bottomright"</span>,</span>
<span id="cb9-38"><a href="#cb9-38" aria-hidden="true" tabindex="-1"></a>       <span class="at">legend =</span> <span class="fu">c</span>(<span class="st">"Cold"</span>,<span class="st">"Warm"</span>),</span>
<span id="cb9-39"><a href="#cb9-39" aria-hidden="true" tabindex="-1"></a>       <span class="at">pch =</span> <span class="dv">19</span>,</span>
<span id="cb9-40"><a href="#cb9-40" aria-hidden="true" tabindex="-1"></a>       <span class="at">col =</span> <span class="fu">c</span>(col_cold, col_warm),</span>
<span id="cb9-41"><a href="#cb9-41" aria-hidden="true" tabindex="-1"></a>       <span class="at">bty =</span> <span class="st">"n"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Rewild-or-Wait---analysing-proportions_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Agresti-Coull CI for each treatment </span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>ci_list <span class="ot">&lt;-</span> <span class="fu">lapply</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(summary_df), <span class="cf">function</span>(i){</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  x <span class="ot">&lt;-</span> summary_df<span class="sc">$</span>total_germ[i]</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  n <span class="ot">&lt;-</span> summary_df<span class="sc">$</span>total_seeds[i]</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  ci <span class="ot">&lt;-</span> <span class="fu">binom.confint</span>(<span class="at">x =</span> x, <span class="at">n =</span> n, <span class="at">methods =</span> <span class="st">"ac"</span>)</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># binom.confint returns a data.frame of 1 row</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">treatment =</span> summary_df<span class="sc">$</span>treatment[i],</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>             <span class="at">est =</span> ci<span class="sc">$</span>mean,</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>             <span class="at">lower =</span> ci<span class="sc">$</span>lower,</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>             <span class="at">upper =</span> ci<span class="sc">$</span>upper,</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>             <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>ci_table <span class="ot">&lt;-</span> <span class="fu">do.call</span>(rbind, ci_list)</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>ci_table<span class="sc">$</span>est <span class="ot">&lt;-</span> <span class="fu">round</span>(ci_table<span class="sc">$</span>est, <span class="dv">3</span>)</span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>ci_table<span class="sc">$</span>lower <span class="ot">&lt;-</span> <span class="fu">round</span>(ci_table<span class="sc">$</span>lower, <span class="dv">3</span>)</span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>ci_table<span class="sc">$</span>upper <span class="ot">&lt;-</span> <span class="fu">round</span>(ci_table<span class="sc">$</span>upper, <span class="dv">3</span>)</span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(ci_table)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  treatment   est lower upper
1      Cold 0.437 0.382 0.493
2      Warm 0.560 0.503 0.615</code></pre>
</div>
</div>
<p><strong>QUESTION:</strong> Explain the plot in your own words. What does each single point represent? Would you say there is a big variation? If tray variation seems larger than expected, what biological factors could cause that (e.g., tray micro-environment, contamination, clumping)?</p>
<p><em>ANSWER</em>:</p>
<p><sub><strong>Possible&nbsp;answer:</strong>&nbsp;The&nbsp;plot&nbsp;shows&nbsp;the&nbsp;germination&nbsp;percentage&nbsp;in&nbsp;each&nbsp;petri&nbsp;dish&nbsp;(or&nbsp;tray)&nbsp;acording&nbsp;to&nbsp;the&nbsp;treatment.&nbsp;Each&nbsp;point&nbsp;represents&nbsp;a&nbsp;petri&nbsp;dish&nbsp;and&nbsp;the&nbsp;number,&nbsp;the&nbsp;amount&nbsp;of&nbsp;successes&nbsp;(seeds&nbsp;that&nbsp;germinated),&nbsp;out&nbsp;of&nbsp;the&nbsp;total&nbsp;seeds.&nbsp;Deciding&nbsp;if&nbsp;a&nbsp;variation&nbsp;is&nbsp;big&nbsp;or&nbsp;small&nbsp;depends&nbsp;on&nbsp;a&nbsp;lot&nbsp;of&nbsp;factors.&nbsp;I&nbsp;would&nbsp;consider&nbsp;discussing&nbsp;that&nbsp;this&nbsp;is&nbsp;a&nbsp;proportion,&nbsp;and&nbsp;therefore&nbsp;ranges&nbsp;from&nbsp;0&nbsp;to&nbsp;1.&nbsp;We&nbsp;are&nbsp;observing&nbsp;variations&nbsp;around&nbsp;0.3&nbsp;(i.e&nbsp;a&nbsp;30%)&nbsp;around&nbsp;the&nbsp;mean&nbsp;value,&nbsp;which&nbsp;could&nbsp;be&nbsp;a&nbsp;meaningful&nbsp;variation.&nbsp;Descritpion&nbsp;of&nbsp;variation&nbsp;always&nbsp;needs&nbsp;to&nbsp;be&nbsp;supported&nbsp;by&nbsp;contextual&nbsp;information.&nbsp;I&nbsp;can&nbsp;envision&nbsp;different&nbsp;factors&nbsp;increasing&nbsp;variability.&nbsp;For&nbsp;example,&nbsp;if&nbsp;the&nbsp;micro-environmental&nbsp;conditions&nbsp;are&nbsp;different&nbsp;between&nbsp;petri&nbsp;dishes,&nbsp;for&nbsp;example,&nbsp;some&nbsp;of&nbsp;them&nbsp;had&nbsp;less&nbsp;water,&nbsp;or&nbsp;were&nbsp;closer&nbsp;to&nbsp;the&nbsp;light&nbsp;source.&nbsp;Some&nbsp;seeds&nbsp;being&nbsp;contaminated&nbsp;might&nbsp;also&nbsp;affect,&nbsp;as&nbsp;well&nbsp;as&nbsp;the&nbsp;density&nbsp;of&nbsp;seeds,&nbsp;which&nbsp;might&nbsp;not&nbsp;be&nbsp;absolutely&nbsp;homogeneous.</sub></p>
<p><strong>QUESTION:</strong> Explain the numbers from the table in your own words. What do you think are the mean, lower and upper? What conclusions can you take from this?</p>
<p><em>ANSWER</em>:</p>
<p><sub><strong>Possible&nbsp;answer:</strong>&nbsp;The&nbsp;table&nbsp;shows&nbsp;the&nbsp;p-hat&nbsp;of&nbsp;each&nbsp;treatment,&nbsp;i.e.,&nbsp;the&nbsp;proportion&nbsp;of&nbsp;germinated&nbsp;seeds&nbsp;estimated&nbsp;in&nbsp;our&nbsp;sample.&nbsp;The&nbsp;cold&nbsp;treatment&nbsp;promoted&nbsp;a&nbsp;germination&nbsp;of&nbsp;43.7%&nbsp;in&nbsp;average,&nbsp;whereas&nbsp;the&nbsp;warm&nbsp;a&nbsp;56%.&nbsp;The&nbsp;lower&nbsp;and&nbsp;upper&nbsp;values&nbsp;correspond&nbsp;to&nbsp;the&nbsp;lower&nbsp;and&nbsp;upper&nbsp;confidence&nbsp;interval&nbsp;limits,&nbsp;calculated&nbsp;using&nbsp;the&nbsp;Agresti-Coull&nbsp;method.&nbsp;This&nbsp;means&nbsp;that&nbsp;we&nbsp;can&nbsp;guarantee&nbsp;that&nbsp;95%&nbsp;of&nbsp;the&nbsp;times,&nbsp;the&nbsp;average&nbsp;of&nbsp;the&nbsp;cold&nbsp;treated&nbsp;seeds&nbsp;germination&nbsp;percentage&nbsp;will&nbsp;be&nbsp;between&nbsp;0.382&nbsp;and&nbsp;0.493.&nbsp;The&nbsp;same&nbsp;for&nbsp;the&nbsp;warm.&nbsp;Therefore&nbsp;we&nbsp;can&nbsp;tell&nbsp;the&nbsp;board&nbsp;that&nbsp;the&nbsp;mean&nbsp;germination&nbsp;is&nbsp;indeed&nbsp;around&nbsp;40&nbsp;and&nbsp;we&nbsp;can&nbsp;guarantee&nbsp;that&nbsp;it&nbsp;will&nbsp;not&nbsp;be&nbsp;under&nbsp;30%,&nbsp;since&nbsp;the&nbsp;lowest&nbsp;limit&nbsp;is&nbsp;higher&nbsp;than&nbsp;0.3.</sub></p>
</section>
<section id="one-sample-binomial-test-ci-for-cold" class="level1">
<h1>6. One-sample binomial test &amp; CI for <code>Cold</code></h1>
<p>Test the policy threshold directly (H0: p = 0.40 or H0: p = 0.30 depending on question). We’ll test both:</p>
<ul>
<li><p>Is <code>Cold</code> significantly different from the decision threshold 0.40?</p></li>
<li><p>Are we 95% confident <code>p &gt; 0.30</code>?</p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Cold</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>cold_idx <span class="ot">&lt;-</span> <span class="fu">which</span>(summary_df<span class="sc">$</span>treatment <span class="sc">==</span> <span class="st">"Cold"</span>)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>x_cold <span class="ot">&lt;-</span> summary_df<span class="sc">$</span>total_germ[cold_idx]</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>n_cold <span class="ot">&lt;-</span> summary_df<span class="sc">$</span>total_seeds[cold_idx]</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Cold: x ="</span>, x_cold, <span class="st">"n ="</span>, n_cold, <span class="st">"p_hat ="</span>, <span class="fu">round</span>(x_cold<span class="sc">/</span>n_cold,<span class="dv">3</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Cold: x = 131 n = 300 p_hat = 0.437 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">binom.test</span>(<span class="at">x =</span> x_cold, <span class="at">n =</span> n_cold, <span class="at">p =</span> <span class="fl">0.40</span>, <span class="at">alternative =</span> <span class="st">"two.sided"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Exact binomial test

data:  x_cold and n_cold
number of successes = 131, number of trials = 300, p-value = 0.1954
alternative hypothesis: true probability of success is not equal to 0.4
95 percent confidence interval:
 0.3797479 0.4948486
sample estimates:
probability of success 
             0.4366667 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">binom.test</span>(<span class="at">x =</span> x_cold, <span class="at">n =</span> n_cold, <span class="at">p =</span> <span class="fl">0.30</span>, <span class="at">alternative =</span> <span class="st">"greater"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Exact binomial test

data:  x_cold and n_cold
number of successes = 131, number of trials = 300, p-value = 3.887e-07
alternative hypothesis: true probability of success is greater than 0.3
95 percent confidence interval:
 0.3885247 1.0000000
sample estimates:
probability of success 
             0.4366667 </code></pre>
</div>
</div>
<p><strong>QUESTION:</strong> Explain the results by answering the two questions above. In the code above, why are we using “<code>two.sided</code>” and “<code>greater</code>”? Explain which information is giving the different tests we did:</p>
<p><em>(if you are not sure what each line is doing, just copy and paste it to the Console above to check it)</em></p>
<p><em>ANSWER</em>:</p>
<p><sub><strong>Possible&nbsp;answer:</strong>&nbsp;For&nbsp;the&nbsp;Cold&nbsp;treatment,&nbsp;we&nbsp;observed&nbsp;131&nbsp;germinated&nbsp;seeds&nbsp;out&nbsp;of&nbsp;300,&nbsp;giving</sub> p<sub>^​≈0.437.&nbsp;When&nbsp;testing&nbsp;against&nbsp;the&nbsp;policy&nbsp;threshold&nbsp;of&nbsp;0.40&nbsp;using&nbsp;a&nbsp;<strong>two-sided&nbsp;binomial&nbsp;test</strong>,&nbsp;the&nbsp;p-value&nbsp;is&nbsp;relatively&nbsp;large&nbsp;(greater&nbsp;than&nbsp;0.05),&nbsp;meaning&nbsp;we&nbsp;do&nbsp;<strong>not</strong>&nbsp;have&nbsp;strong&nbsp;evidence&nbsp;that&nbsp;the&nbsp;true&nbsp;germination&nbsp;rate&nbsp;is&nbsp;different&nbsp;from&nbsp;0.40.&nbsp;In&nbsp;other&nbsp;words,&nbsp;Cold&nbsp;is&nbsp;statistically&nbsp;compatible&nbsp;with&nbsp;the&nbsp;0.40&nbsp;threshold.&nbsp;When&nbsp;testing&nbsp;whether&nbsp;we&nbsp;are&nbsp;confident&nbsp;that</sub> p&gt;0.30p &gt; 0.30p<sub>&gt;0.30&nbsp;using&nbsp;a&nbsp;<strong>one-sided&nbsp;(“greater”)&nbsp;test</strong>,&nbsp;the&nbsp;p-value&nbsp;is&nbsp;very&nbsp;small,&nbsp;meaning&nbsp;we&nbsp;have&nbsp;strong&nbsp;evidence&nbsp;that&nbsp;the&nbsp;true&nbsp;germination&nbsp;rate&nbsp;is&nbsp;above&nbsp;0.30.&nbsp;This&nbsp;suggests&nbsp;we&nbsp;can&nbsp;be&nbsp;reasonably&nbsp;confident&nbsp;that&nbsp;Cold&nbsp;exceeds&nbsp;the&nbsp;minimum&nbsp;safety&nbsp;threshold&nbsp;required&nbsp;by&nbsp;the&nbsp;Board.&nbsp;The&nbsp;Agresti–Coull&nbsp;95%&nbsp;confidence&nbsp;interval&nbsp;provides&nbsp;a&nbsp;range&nbsp;of&nbsp;plausible&nbsp;values&nbsp;for&nbsp;the&nbsp;true&nbsp;germination&nbsp;proportion.&nbsp;Since&nbsp;the&nbsp;lower&nbsp;bound&nbsp;is&nbsp;above&nbsp;0.30,&nbsp;we&nbsp;can&nbsp;say&nbsp;we&nbsp;are&nbsp;approximately&nbsp;95%&nbsp;confident&nbsp;that&nbsp;true&nbsp;germination&nbsp;is&nbsp;greater&nbsp;than&nbsp;0.30.&nbsp;However,&nbsp;because&nbsp;the&nbsp;CI&nbsp;includes&nbsp;0.40,&nbsp;we&nbsp;cannot&nbsp;be&nbsp;certain&nbsp;that&nbsp;Cold&nbsp;clearly&nbsp;exceeds&nbsp;the&nbsp;management&nbsp;threshold&nbsp;of&nbsp;0.40.</sub></p>
<ul>
<li><p><sub><code>binom.test(x = x_cold, n = n_cold, p = 0.40, alternative = "two.sided")</code>&nbsp;:&nbsp;This&nbsp;tests&nbsp;whether&nbsp;the&nbsp;true&nbsp;germination&nbsp;probability&nbsp;is&nbsp;different&nbsp;from&nbsp;0.40&nbsp;in&nbsp;either&nbsp;direction&nbsp;(higher&nbsp;or&nbsp;lower).&nbsp;We&nbsp;use&nbsp;<code>"two.sided"</code>&nbsp;because&nbsp;the&nbsp;question&nbsp;is:&nbsp;<em>Is&nbsp;Cold&nbsp;significantly&nbsp;different&nbsp;from&nbsp;0.40?</em>&nbsp;We&nbsp;are&nbsp;not&nbsp;assuming&nbsp;it&nbsp;must&nbsp;be&nbsp;higher&nbsp;or&nbsp;lower,&nbsp;just&nbsp;different.</sub></p></li>
<li><p><sub><code>binom.test(x = x_cold, n = n_cold, p = 0.30, alternative = "greater")</code>&nbsp;:&nbsp;This&nbsp;tests&nbsp;whether&nbsp;the&nbsp;true&nbsp;germination&nbsp;probability&nbsp;is&nbsp;greater&nbsp;than&nbsp;0.30.&nbsp;We&nbsp;use&nbsp;<code>"greater"</code>&nbsp;because&nbsp;the&nbsp;policy&nbsp;question&nbsp;is&nbsp;directional:&nbsp;we&nbsp;want&nbsp;to&nbsp;know&nbsp;whether&nbsp;germination&nbsp;exceeds&nbsp;0.30,&nbsp;not&nbsp;whether&nbsp;it&nbsp;is&nbsp;simply&nbsp;different&nbsp;from&nbsp;it.</sub></p></li>
</ul>
</section>
<section id="one-sample-binomial-test-ci-for-warm" class="level1">
<h1>7. One-sample binomial test &amp; CI for <code>Warm</code></h1>
<p>Test the policy threshold directly (H0: p = 0.40 or H0: p = 0.30 depending on question). We’ll test both:</p>
<ul>
<li><p>Is <code>Warm</code>significantly different from the decision threshold 0.40?</p></li>
<li><p>Are we 95% confident <code>p &gt; 0.30</code>?</p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Warm</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>warm_idx <span class="ot">&lt;-</span> <span class="fu">which</span>(summary_df<span class="sc">$</span>treatment <span class="sc">==</span> <span class="st">"Warm"</span>)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>x_warm <span class="ot">&lt;-</span> summary_df<span class="sc">$</span>total_germ[warm_idx]</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>n_warm <span class="ot">&lt;-</span> summary_df<span class="sc">$</span>total_seeds[warm_idx]</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Warm: x ="</span>, x_warm, <span class="st">"n ="</span>, n_warm, <span class="st">"p_hat ="</span>, <span class="fu">round</span>(x_warm<span class="sc">/</span>n_warm,<span class="dv">3</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Warm: x = 168 n = 300 p_hat = 0.56 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">binom.test</span>(<span class="at">x =</span> x_warm, <span class="at">n =</span> n_warm, <span class="at">p =</span> <span class="fl">0.40</span>, <span class="at">alternative =</span> <span class="st">"two.sided"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Exact binomial test

data:  x_warm and n_warm
number of successes = 168, number of trials = 300, p-value = 2.405e-08
alternative hypothesis: true probability of success is not equal to 0.4
95 percent confidence interval:
 0.5018048 0.6169985
sample estimates:
probability of success 
                  0.56 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">binom.test</span>(<span class="at">x =</span> x_warm, <span class="at">n =</span> n_warm, <span class="at">p =</span> <span class="fl">0.30</span>, <span class="at">alternative =</span> <span class="st">"greater"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Exact binomial test

data:  x_warm and n_warm
number of successes = 168, number of trials = 300, p-value &lt; 2.2e-16
alternative hypothesis: true probability of success is greater than 0.3
95 percent confidence interval:
 0.510905 1.000000
sample estimates:
probability of success 
                  0.56 </code></pre>
</div>
</div>
<p><strong>QUESTION:</strong> Explain the results as you did before with the cold treatment. Answer the two questions above. Explain which information is giving the different tests we did:</p>
<p><em>ANSWER</em>:</p>
<p><sub><strong>Possible&nbsp;answer:</strong>&nbsp;For&nbsp;the&nbsp;Warm&nbsp;treatment,&nbsp;we&nbsp;observed&nbsp;168&nbsp;germinated&nbsp;seeds&nbsp;out&nbsp;of&nbsp;300,&nbsp;giving</sub> p h<sub>at&nbsp;of&nbsp;0.456.&nbsp;When&nbsp;testing&nbsp;against&nbsp;the&nbsp;policy&nbsp;threshold&nbsp;of&nbsp;0.40&nbsp;using&nbsp;a&nbsp;<strong>two-sided&nbsp;binomial&nbsp;test</strong>,&nbsp;the&nbsp;p-value&nbsp;smaller&nbsp;than&nbsp;0.05,&nbsp;meaning&nbsp;we&nbsp;do&nbsp;have&nbsp;enough&nbsp;evidence&nbsp;that&nbsp;the&nbsp;true&nbsp;germination&nbsp;rate&nbsp;is&nbsp;different&nbsp;from&nbsp;0.40.&nbsp;In&nbsp;other&nbsp;words,&nbsp;the&nbsp;Warm&nbsp;treatment&nbsp;is&nbsp;statistically&nbsp;“incompatible”&nbsp;with&nbsp;the&nbsp;0.40&nbsp;threshold,&nbsp;the&nbsp;germination&nbsp;percentage&nbsp;is&nbsp;not&nbsp;0.4,&nbsp;it&nbsp;is&nbsp;bigger.&nbsp;When&nbsp;testing&nbsp;whether&nbsp;we&nbsp;are&nbsp;confident&nbsp;that</sub> p&gt;0.30p &gt; <sub>using&nbsp;a&nbsp;<strong>one-sided&nbsp;(“greater”)&nbsp;test</strong>,&nbsp;the&nbsp;p-value&nbsp;is&nbsp;also&nbsp;very&nbsp;small,&nbsp;meaning&nbsp;we&nbsp;have&nbsp;strong&nbsp;evidence&nbsp;that&nbsp;the&nbsp;true&nbsp;germination&nbsp;rate&nbsp;is&nbsp;above&nbsp;0.30.&nbsp;This&nbsp;suggests&nbsp;we&nbsp;can&nbsp;be&nbsp;reasonably&nbsp;confident&nbsp;that&nbsp;Warm&nbsp;exceeds&nbsp;the&nbsp;minimum&nbsp;safety&nbsp;threshold&nbsp;required&nbsp;by&nbsp;the&nbsp;Board.&nbsp;The&nbsp;Agresti–Coull&nbsp;95%&nbsp;confidence&nbsp;interval&nbsp;provides&nbsp;a&nbsp;range&nbsp;of&nbsp;plausible&nbsp;values&nbsp;for&nbsp;the&nbsp;true&nbsp;germination&nbsp;proportion.&nbsp;Since&nbsp;the&nbsp;lower&nbsp;bound&nbsp;is&nbsp;above&nbsp;0.30,&nbsp;we&nbsp;can&nbsp;say&nbsp;we&nbsp;are&nbsp;approximately&nbsp;95%&nbsp;confident&nbsp;that&nbsp;true&nbsp;germination&nbsp;is&nbsp;greater&nbsp;than&nbsp;0.30.&nbsp;However,&nbsp;because&nbsp;the&nbsp;CI&nbsp;includes&nbsp;0.40,&nbsp;we&nbsp;cannot&nbsp;be&nbsp;certain&nbsp;that&nbsp;Cold&nbsp;clearly&nbsp;exceeds&nbsp;the&nbsp;management&nbsp;threshold&nbsp;of&nbsp;0.40.</sub></p>
<ul>
<li><p><sub><code>binom.test(x = x_cold, n = n_cold, p = 0.40, alternative = "two.sided")</code>&nbsp;:&nbsp;This&nbsp;tests&nbsp;whether&nbsp;the&nbsp;true&nbsp;germination&nbsp;probability&nbsp;is&nbsp;different&nbsp;from&nbsp;0.40&nbsp;in&nbsp;either&nbsp;direction&nbsp;(higher&nbsp;or&nbsp;lower).&nbsp;We&nbsp;use&nbsp;<code>"two.sided"</code>&nbsp;because&nbsp;the&nbsp;question&nbsp;is:&nbsp;<em>Is&nbsp;Cold&nbsp;significantly&nbsp;different&nbsp;from&nbsp;0.40?</em>&nbsp;We&nbsp;are&nbsp;not&nbsp;assuming&nbsp;it&nbsp;must&nbsp;be&nbsp;higher&nbsp;or&nbsp;lower,&nbsp;just&nbsp;different.</sub></p></li>
<li><p><sub><code>binom.test(x = x_cold, n = n_cold, p = 0.30, alternative = "greater")</code>&nbsp;:&nbsp;This&nbsp;tests&nbsp;whether&nbsp;the&nbsp;true&nbsp;germination&nbsp;probability&nbsp;is&nbsp;greater&nbsp;than&nbsp;0.30.&nbsp;We&nbsp;use&nbsp;<code>"greater"</code>&nbsp;because&nbsp;the&nbsp;policy&nbsp;question&nbsp;is&nbsp;directional:&nbsp;we&nbsp;want&nbsp;to&nbsp;know&nbsp;whether&nbsp;germination&nbsp;exceeds&nbsp;0.30,&nbsp;not&nbsp;whether&nbsp;it&nbsp;is&nbsp;simply&nbsp;different&nbsp;from&nbsp;it.</sub></p></li>
</ul>
<p><sub>Warm&nbsp;shows&nbsp;strong&nbsp;statistical&nbsp;evidence&nbsp;of&nbsp;higher&nbsp;germination&nbsp;(p̂&nbsp;≈&nbsp;0.56;&nbsp;95%&nbsp;CI&nbsp;≈&nbsp;0.50–0.62),&nbsp;so&nbsp;it&nbsp;exceeds&nbsp;the&nbsp;Board’s&nbsp;minimum&nbsp;thresholds&nbsp;—&nbsp;but&nbsp;remember&nbsp;to&nbsp;combine&nbsp;these&nbsp;numbers&nbsp;with&nbsp;biological&nbsp;realism&nbsp;(independence,&nbsp;lab→field&nbsp;differences,&nbsp;cost)&nbsp;before&nbsp;recommending&nbsp;full&nbsp;reintroduction.&nbsp;Additional&nbsp;takeaway:&nbsp;Tests&nbsp;need&nbsp;to&nbsp;be&nbsp;designed&nbsp;carefully&nbsp;to&nbsp;provide&nbsp;the&nbsp;answers&nbsp;we&nbsp;actually&nbsp;need.</sub></p>
</section>
<section id="compare-cold-vs-warm-two-sample-effect-size-tests" class="level1">
<h1>Compare Cold vs Warm (two-sample) — effect size &amp; tests</h1>
<p>So, you have tested weather youtr proposed tests would satisfy the certanity conditions the board imposed. Could you also explain them using one of them is better than the other? Are the treatments truly different? Note that in our previous session we also tested if treatments were significantly different, but that was for continuous data (the sugar contents of strawberry). This time we need a test for proportion data, and therefore we will use a different strategy to capture the probability of making an error on accepting or discarding H0. <strong>Personal reflection:</strong> think about the differences between what we did last week and this type of data. How would you propose to test if the differences are significant in this case?</p>
<p>We will now test whether <code>Warm</code> improves germination compared to <code>Cold</code>. We will show both <code>prop.test</code> (chi-square approx) and Fisher exact (exact).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ---- Compare Cold vs Warm: contingency, prop.test and Fisher (base R) ----</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(x_cold, x_warm)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">c</span>(n_cold, n_warm)</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="co"># observed contingency matrix</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>mat <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(x[<span class="dv">1</span>], n[<span class="dv">1</span>]<span class="sc">-</span>x[<span class="dv">1</span>],</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>                x[<span class="dv">2</span>], n[<span class="dv">2</span>]<span class="sc">-</span>x[<span class="dv">2</span>]), <span class="at">nrow =</span> <span class="dv">2</span>, <span class="at">byrow =</span> <span class="cn">TRUE</span>)</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(mat) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Cold"</span>,<span class="st">"Warm"</span>)</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(mat) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Germ"</span>,<span class="st">"NoGerm"</span>)</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Observed 2 x 2 contingency matrix:</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Observed 2 x 2 contingency matrix:</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(mat)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Germ NoGerm
Cold  131    169
Warm  168    132</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># pooled proportion under H0</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>pooled_p <span class="ot">&lt;-</span> <span class="fu">sum</span>(x)<span class="sc">/</span><span class="fu">sum</span>(n)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Pooled proportion (under H0 = same p):"</span>, <span class="fu">round</span>(pooled_p, <span class="dv">3</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Pooled proportion (under H0 = same p): 0.498 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># prop.test (chi-square approx)</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>prop_res <span class="ot">&lt;-</span> <span class="fu">prop.test</span>(<span class="at">x =</span> x, <span class="at">n =</span> n, <span class="at">correct =</span> <span class="cn">FALSE</span>)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">prop.test (chi-square) statistic:</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
prop.test (chi-square) statistic:</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(prop_res<span class="sc">$</span>statistic)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>X-squared 
 9.126768 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"p-value:"</span>, <span class="fu">format.pval</span>(prop_res<span class="sc">$</span>p.value), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>p-value: 0.002519 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fisher exact (exact)</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>fisher_res <span class="ot">&lt;-</span> <span class="fu">fisher.test</span>(mat)</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Fisher exact p-value:</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Fisher exact p-value:</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">format.pval</span>(fisher_res<span class="sc">$</span>p.value))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "0.0032554"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># effect size: Warm - Cold (make positive)</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>p_warm <span class="ot">&lt;-</span> x[<span class="dv">2</span>] <span class="sc">/</span> n[<span class="dv">2</span>]</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>p_cold <span class="ot">&lt;-</span> x[<span class="dv">1</span>] <span class="sc">/</span> n[<span class="dv">1</span>]</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>diff_prop <span class="ot">&lt;-</span> p_warm <span class="sc">-</span> p_cold</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Effect size (Warm - Cold):"</span>, <span class="fu">round</span>(diff_prop, <span class="dv">3</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Effect size (Warm - Cold): 0.123 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># prop.test CI corresponds to (p1 - p2) where p1 is first group passed to prop.test</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="co"># To get CI for Warm - Cold we run prop.test with the Warm counts first:</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>prop_res_warmfirst <span class="ot">&lt;-</span> <span class="fu">prop.test</span>(<span class="at">x =</span> <span class="fu">c</span>(x[<span class="dv">2</span>], x[<span class="dv">1</span>]), <span class="at">n =</span> <span class="fu">c</span>(n[<span class="dv">2</span>], n[<span class="dv">1</span>]), <span class="at">correct =</span> <span class="cn">FALSE</span>)</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>ci_diff <span class="ot">&lt;-</span> prop_res_warmfirst<span class="sc">$</span>conf.int</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Approx 95% CI for (Warm - Cold):"</span>, <span class="fu">round</span>(ci_diff[<span class="dv">1</span>],<span class="dv">3</span>), <span class="st">"to"</span>, <span class="fu">round</span>(ci_diff[<span class="dv">2</span>],<span class="dv">3</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Approx 95% CI for (Warm - Cold): 0.044 to 0.203 </code></pre>
</div>
</div>
<p><strong>QUESTION.</strong> Take a look at the outputs. Explain the following results:</p>
<ul>
<li>Why is the H0 0.498? (or any other observed value in case you changed the numbers)</li>
</ul>
<p><em>ANSWER</em>:</p>
<p><sub><strong>Possible&nbsp;answer:</strong>&nbsp;That&nbsp;0.498&nbsp;is&nbsp;the&nbsp;<em>pooled&nbsp;proportion</em>&nbsp;=&nbsp;total&nbsp;germinated&nbsp;/&nbsp;total&nbsp;seeds&nbsp;across&nbsp;both&nbsp;treatments.&nbsp;Under&nbsp;H₀&nbsp;(same&nbsp;p&nbsp;in&nbsp;both&nbsp;groups)&nbsp;the&nbsp;expected&nbsp;cell&nbsp;counts&nbsp;are&nbsp;computed&nbsp;from&nbsp;that&nbsp;pooled&nbsp;p.</sub></p>
<ul>
<li>How many seeds did not germinate under the warm treatment? (this question is to make sure you know where the observed contingency matrix is)</li>
</ul>
<p><em>ANSWER</em>:</p>
<p><sub><strong>Possible&nbsp;answer:</strong>&nbsp;&nbsp;132&nbsp;seeds&nbsp;(Warm&nbsp;row:&nbsp;Germ&nbsp;=&nbsp;168,&nbsp;NoGerm&nbsp;=&nbsp;132).</sub></p>
<ul>
<li>Is the p-value of the prop.test (chi-square) different than the Fisher exact test? Is the conclusion the same?</li>
</ul>
<p><em>ANSWER</em>:</p>
<p><sub><strong>Possible&nbsp;answer:</strong></sub> T<sub>hey&nbsp;differ&nbsp;slightly&nbsp;(≈0.0025&nbsp;vs&nbsp;≈0.0033)&nbsp;because&nbsp;<code>prop.test</code>&nbsp;uses&nbsp;a&nbsp;chi-square&nbsp;approximation&nbsp;while&nbsp;Fisher&nbsp;is&nbsp;exact.&nbsp;The&nbsp;conclusion&nbsp;is&nbsp;the&nbsp;same:&nbsp;both&nbsp;give&nbsp;small&nbsp;p-values&nbsp;→&nbsp;reject&nbsp;H₀.&nbsp;The&nbsp;Fisher&nbsp;exact&nbsp;test&nbsp;uses&nbsp;the&nbsp;observed&nbsp;and&nbsp;expected&nbsp;frequesncies&nbsp;to&nbsp;calculate&nbsp;the&nbsp;p-value,&nbsp;whereas&nbsp;the&nbsp;p-value&nbsp;calculation&nbsp;from&nbsp;the&nbsp;chi-square&nbsp;estimation&nbsp;relies&nbsp;on&nbsp;how&nbsp;good&nbsp;the&nbsp;estimation&nbsp;of&nbsp;the&nbsp;chi-square&nbsp;distribution&nbsp;fits&nbsp;the&nbsp;data.&nbsp;When&nbsp;the&nbsp;sample&nbsp;size&nbsp;is&nbsp;small,&nbsp;the&nbsp;Fisher&nbsp;exact&nbsp;test&nbsp;is&nbsp;more&nbsp;reliable,&nbsp;but&nbsp;it&nbsp;is&nbsp;very&nbsp;usual&nbsp;that&nbsp;both&nbsp;get&nbsp;you&nbsp;to&nbsp;the&nbsp;same&nbsp;conclusion.&nbsp;Takeaway&nbsp;from&nbsp;this&nbsp;is&nbsp;that&nbsp;there&nbsp;are&nbsp;multiple&nbsp;ways&nbsp;of&nbsp;calculating&nbsp;how&nbsp;common&nbsp;an&nbsp;event&nbsp;is,&nbsp;and&nbsp;they&nbsp;all&nbsp;have&nbsp;limitations.</sub></p>
<ul>
<li>What does it mean that the effect size (Warm-Cold) is 0.123 (or any other if you changed the numbers)? Is this increase biologically meaningful? Write a sentence including the effect size and CI with your own words.</li>
</ul>
<p><em>ANSWER</em>:</p>
<p><sub><strong>Possible&nbsp;answer:</strong>&nbsp;Effect&nbsp;=&nbsp;0.123&nbsp;means&nbsp;Warm&nbsp;increased&nbsp;germination&nbsp;by&nbsp;12.3&nbsp;percentage&nbsp;points&nbsp;(Warm&nbsp;≈&nbsp;0.560&nbsp;vs&nbsp;Cold&nbsp;≈&nbsp;0.437).&nbsp;The&nbsp;95%&nbsp;CI&nbsp;≈&nbsp;(0.044,&nbsp;0.203)&nbsp;shows&nbsp;the&nbsp;increase&nbsp;is&nbsp;statistically&nbsp;significant,&nbsp;but&nbsp;practical&nbsp;significance&nbsp;is&nbsp;borderline,&nbsp;since&nbsp;an&nbsp;increase&nbsp;on&nbsp;12%&nbsp;germination&nbsp;might&nbsp;not&nbsp;be&nbsp;biologically&nbsp;enought&nbsp;to&nbsp;make&nbsp;a&nbsp;difference.&nbsp;It&nbsp;will&nbsp;depend&nbsp;of&nbsp;the&nbsp;cost&nbsp;of&nbsp;the&nbsp;Warm&nbsp;treatment&nbsp;to&nbsp;decide&nbsp;if&nbsp;using&nbsp;this&nbsp;treatment&nbsp;is&nbsp;cost-efficient.&nbsp;We&nbsp;are&nbsp;95%&nbsp;sure&nbsp;that&nbsp;the&nbsp;warm&nbsp;treatment&nbsp;increases&nbsp;a&nbsp;12.3%&nbsp;the&nbsp;germination&nbsp;percentage,&nbsp;and&nbsp;even&nbsp;though&nbsp;this&nbsp;is&nbsp;small,&nbsp;it&nbsp;is&nbsp;a&nbsp;statistically&nbsp;significant&nbsp;increase.</sub></p>
</section>
<section id="simulation-demo-what-does-a-p-value-really-mean" class="level1">
<h1>8. Simulation demo: what does a p-value really mean?</h1>
<p>We tested if germination under the cold treatment was equal to 0.40. When doing this, the binomial test gave us a p-value. But what does that number actually represent? (Make sure you know where this number was in the questions above).</p>
<p>This p-value represents the following: If the true germination probability really were 0.40, how often would we observe results as extreme as ours just by random chance? Let’s simulate it!</p>
<p>We will assume that true germination probability is 0.40 and we planted n_cold seeds (300). If that is true, then the number of germinated seeds follows a binomial distribution. We will simulate many repeated experiments under that assumption.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Number of simulated experiments</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>B <span class="ot">&lt;-</span> <span class="dv">5000</span>  </span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulate B experiments under H0: p = 0.40</span></span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>simulated_successes <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(B, <span class="at">size =</span> n_cold, <span class="at">prob =</span> <span class="fl">0.40</span>)</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Look at first six simulated outcomes (numer of seeds germinated)</span></span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(simulated_successes)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 138 124 119 109 114 119</code></pre>
</div>
</div>
<p>What this does is generate a random numbers dataset from a binomial distribution. Each number represents one hypothetical experiment (how many seeds germinated from the 300 we used). We repeat the experiment 5,000 times.</p>
<p>What we actually observed was:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>x_cold</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 131</code></pre>
</div>
</div>
<p>Now we ask: In our simulated world (where p = 0.40), how often do we see results as far away from expectation as our real data? The expected number of successes under H0 is:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>expected_null <span class="ot">&lt;-</span> n_cold <span class="sc">*</span> <span class="fl">0.40</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>expected_null</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 120</code></pre>
</div>
</div>
<p>Now we compute how extreme our observation was:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>observed_distance <span class="ot">&lt;-</span> <span class="fu">abs</span>(x_cold <span class="sc">-</span> expected_null)</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>observed_distance</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 11</code></pre>
</div>
</div>
<p>Now count how many simulations were at least that extreme:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>p_simulated <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">abs</span>(simulated_successes <span class="sc">-</span> expected_null) <span class="sc">&gt;=</span> observed_distance)</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>p_simulated</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.223</code></pre>
</div>
</div>
<p>This the proportion of simulated experiments that were as extreme as or more extreme than what we observed. That is the p-value, and it should be close to the p-value from:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">binom.test</span>(x_cold, n_cold, <span class="at">p =</span> <span class="fl">0.40</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Exact binomial test

data:  x_cold and n_cold
number of successes = 131, number of trials = 300, p-value = 0.1954
alternative hypothesis: true probability of success is not equal to 0.4
95 percent confidence interval:
 0.3797479 0.4948486
sample estimates:
probability of success 
             0.4366667 </code></pre>
</div>
</div>
<p>To consolidate these numbers take a look at this histogram. The red line is our observed result. The p-value is the area of the histogram in both tails beyond this distance.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(simulated_successes,</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">breaks =</span> <span class="dv">30</span>,</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Simulated outcomes under H0 (p = 0.40)"</span>,</span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Number of germinated seeds out of 300"</span>)</span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> x_cold, <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lwd =</span> <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Rewild-or-Wait---analysing-proportions_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>TEST YOURSELF WITH THESE QUESTIONS:</strong></p>
<ul>
<li>If we increased <code>n_cold</code> (sample size), would the spread of simulated results get wider or narrower?</li>
</ul>
<p><em>ANSWER</em>:</p>
<p><sub><strong>Possible&nbsp;answer:</strong>&nbsp;The&nbsp;spread&nbsp;of&nbsp;<em>proportions</em>&nbsp;shrinks&nbsp;like</sub> sqrt(p(1-p)/n<sub>)​,&nbsp;so&nbsp;the&nbsp;proportion&nbsp;values&nbsp;become&nbsp;<strong>narrower</strong>&nbsp;(more&nbsp;precise).</sub></p>
<ul>
<li>With a larger sample size, would extreme deviations become more or less likely?</li>
</ul>
<p><em>ANSWER</em>:</p>
<p><sub><strong>Possible&nbsp;answer:</strong>&nbsp;Less&nbsp;likely.&nbsp;Larger</sub> n <sub>makes&nbsp;the&nbsp;sample&nbsp;proportion&nbsp;cluster&nbsp;tightly&nbsp;around&nbsp;the&nbsp;true</sub> p<sub>,&nbsp;so&nbsp;large&nbsp;proportional&nbsp;deviations&nbsp;from&nbsp;the&nbsp;null&nbsp;are&nbsp;rarer.&nbsp;(In&nbsp;absolute&nbsp;counts&nbsp;a&nbsp;big&nbsp;deviation&nbsp;may&nbsp;still&nbsp;appear&nbsp;but&nbsp;is&nbsp;judged&nbsp;relative&nbsp;to&nbsp;a&nbsp;larger&nbsp;SD.)</sub></p>
<ul>
<li>If the true proportion of germinated seeds were 0.38 instead of 0.40, would the p-value necessarily be small?</li>
</ul>
<p><em>ANSWER</em>:</p>
<p><sub><strong>Possible&nbsp;answer:</strong>&nbsp;No.&nbsp;A&nbsp;p-value&nbsp;depends&nbsp;on&nbsp;the&nbsp;<em>observed&nbsp;data</em>&nbsp;and&nbsp;the&nbsp;sample&nbsp;size.&nbsp;A&nbsp;true&nbsp;difference&nbsp;of&nbsp;0.02&nbsp;(0.38&nbsp;vs&nbsp;0.40)&nbsp;is&nbsp;small;&nbsp;with</sub> n=300 <sub>it’s&nbsp;unlikely&nbsp;to&nbsp;give&nbsp;a&nbsp;very&nbsp;small&nbsp;p&nbsp;unless&nbsp;the&nbsp;observed&nbsp;outcome&nbsp;happens&nbsp;to&nbsp;be&nbsp;far&nbsp;from&nbsp;0.40.&nbsp;Larger&nbsp;samples&nbsp;can&nbsp;detect&nbsp;such&nbsp;small&nbsp;differences,&nbsp;small&nbsp;samples&nbsp;usually&nbsp;cannot.&nbsp;Global&nbsp;takeaway:&nbsp;bigger&nbsp;n&nbsp;means&nbsp;more&nbsp;precision&nbsp;for&nbsp;proportions;&nbsp;small&nbsp;effect&nbsp;sizes&nbsp;can&nbsp;be&nbsp;statistically&nbsp;detectable&nbsp;only&nbsp;with&nbsp;sufficiently&nbsp;large&nbsp;samples,&nbsp;so&nbsp;always&nbsp;interpret&nbsp;p-values&nbsp;together&nbsp;with&nbsp;effect&nbsp;size&nbsp;and&nbsp;sample&nbsp;size.</sub></p>
</section>
<section id="the-final-decision-rewild-or-wait" class="level1">
<h1>9. The final decision: rewild or wait?</h1>
<p>You are now in the final meeting of the <strong>Alpine Rewilding Task Force</strong>. You must recommend one action for <em>Eritrichium nanum</em>. But the situation is not simple. Additional realities:</p>
<ul>
<li><p>Your pilot experiment revealed that <strong>Warm treatment increases germination</strong> — but it is expensive and labour-intensive.</p></li>
<li><p>❄ <strong>Cold treatment is cheap</strong> — but germination may be borderline.</p></li>
<li><p>⏳ <strong>If you delay reintroduction</strong>, seeds will remain in storage for another year. Seed viability typically declines slightly with age. Waiting may reduce germination success next season, but we don’t know at which rate. However, you have the opportunity to improve the warm treatment and improve field survive methods, as well as produce more seeds with artificial seeds production if that is important.</p></li>
<li><p>💰 The conservation budget allows only one full reintroduction attempt in the next two years.</p></li>
</ul>
<p>Write one paragraph (2–4 sentences) including:</p>
<ul>
<li><p>The statistical test(s) used (binomial test, prop.test, Fisher, CI)</p></li>
<li><p>Key numeric evidence (p-value, CI bounds, effect size)</p></li>
<li><p>Your recommendation defensible with numbers.</p></li>
<li><p>A short biological justification (cost, ageing risk, uncertainty tolerance)</p></li>
</ul>
<p><em>ANSWER</em>:</p>
<p><sub><strong>Possible&nbsp;answer:</strong>&nbsp;I&nbsp;examined&nbsp;the&nbsp;pilot&nbsp;data&nbsp;with&nbsp;exact&nbsp;binomial&nbsp;tests&nbsp;for&nbsp;each&nbsp;treatment&nbsp;and&nbsp;a&nbsp;two-sample&nbsp;comparison&nbsp;(prop.test&nbsp;and&nbsp;Fisher’s&nbsp;exact);&nbsp;the&nbsp;two-sample&nbsp;tests&nbsp;give&nbsp;<strong>p&nbsp;≈&nbsp;0.0025–0.0033</strong>&nbsp;and&nbsp;the&nbsp;estimated&nbsp;effect&nbsp;size&nbsp;<strong>Warm&nbsp;−&nbsp;Cold&nbsp;≈&nbsp;0.123</strong>&nbsp;with&nbsp;an&nbsp;approximate&nbsp;95%&nbsp;CI&nbsp;<strong>≈&nbsp;(0.044,&nbsp;0.203)</strong>.&nbsp;Statistically,&nbsp;Warm&nbsp;clearly&nbsp;outperforms&nbsp;Cold&nbsp;(the&nbsp;CI&nbsp;excludes&nbsp;0&nbsp;and&nbsp;Warm&nbsp;is&nbsp;also&nbsp;individually&nbsp;&gt;0.40),&nbsp;but&nbsp;the&nbsp;lower&nbsp;CI&nbsp;bound&nbsp;(≈4.4%)&nbsp;falls&nbsp;short&nbsp;of&nbsp;the&nbsp;Board’s&nbsp;<strong>10%&nbsp;practical&nbsp;threshold</strong>,&nbsp;so&nbsp;practical&nbsp;benefit&nbsp;is&nbsp;promising&nbsp;but&nbsp;not&nbsp;guaranteed.&nbsp;Given&nbsp;the&nbsp;budget/seed&nbsp;constraints&nbsp;and&nbsp;the&nbsp;risk&nbsp;of&nbsp;seed&nbsp;ageing&nbsp;if&nbsp;we&nbsp;delay,&nbsp;my&nbsp;defensible&nbsp;compromise&nbsp;is&nbsp;<strong>a&nbsp;limited&nbsp;pilot&nbsp;release&nbsp;using&nbsp;the&nbsp;Warm&nbsp;protocol&nbsp;(small-scale&nbsp;reintroduction,&nbsp;intensive&nbsp;monitoring)</strong>&nbsp;rather&nbsp;than&nbsp;a&nbsp;full-scale&nbsp;attempt&nbsp;or&nbsp;outright&nbsp;delay&nbsp;—&nbsp;this&nbsp;uses&nbsp;fewer&nbsp;seeds,&nbsp;produces&nbsp;field&nbsp;evidence&nbsp;to&nbsp;reduce&nbsp;uncertainty,&nbsp;and&nbsp;preserves&nbsp;the&nbsp;option&nbsp;to&nbsp;scale&nbsp;up&nbsp;next&nbsp;year&nbsp;if&nbsp;early&nbsp;survival&nbsp;confirms&nbsp;the&nbsp;lab&nbsp;gains.&nbsp;Biological&nbsp;rationale:&nbsp;Warm&nbsp;gives&nbsp;higher,&nbsp;more&nbsp;synchronous&nbsp;germination&nbsp;(so&nbsp;higher&nbsp;establishment&nbsp;potential),&nbsp;but&nbsp;because&nbsp;it&nbsp;is&nbsp;costlier&nbsp;and&nbsp;uncertainty&nbsp;around&nbsp;the&nbsp;true&nbsp;gain&nbsp;remains,&nbsp;a&nbsp;staged&nbsp;pilot&nbsp;balances&nbsp;conservation&nbsp;ambition&nbsp;with&nbsp;prudent&nbsp;risk&nbsp;management.&nbsp;It&nbsp;is&nbsp;worth&nbsp;mentioning&nbsp;that&nbsp;because&nbsp;germination&nbsp;percentages&nbsp;are&nbsp;well&nbsp;below&nbsp;100%,&nbsp;the&nbsp;number&nbsp;of&nbsp;seeds&nbsp;required&nbsp;scales&nbsp;quickly&nbsp;with&nbsp;the&nbsp;number&nbsp;of&nbsp;individuals&nbsp;we&nbsp;aim&nbsp;to&nbsp;establish;&nbsp;therefore,&nbsp;if&nbsp;the&nbsp;target&nbsp;population&nbsp;size&nbsp;is&nbsp;large&nbsp;or&nbsp;the&nbsp;Warm&nbsp;treatment&nbsp;substantially&nbsp;increases&nbsp;costs,&nbsp;we&nbsp;may&nbsp;not&nbsp;have&nbsp;enough&nbsp;seeds&nbsp;(or&nbsp;budget)&nbsp;to&nbsp;justify&nbsp;a&nbsp;full&nbsp;reintroduction,&nbsp;which&nbsp;could&nbsp;shift&nbsp;the&nbsp;decision&nbsp;toward&nbsp;a&nbsp;smaller&nbsp;pilot&nbsp;or&nbsp;delaying&nbsp;until&nbsp;seed&nbsp;stock&nbsp;and&nbsp;resources&nbsp;are&nbsp;sufficient.</sub></p>
<p><strong>TEST YOUR RESPONSE.</strong> The following code will ask you to choose between Rewild or Wait , as welll as the treatment applied to germinate the seeds considering different elements such as the cost of the treatments, the benefits and drawbacks of waiting, etc. Check if your decision was the right call!</p>
<p><em>NOTE: The code needs your input. Run the chunk and check the console to choose options.</em></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ------------------------------</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Interactive Decision Simulator </span></span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Rewild now? Wait one year?</span></span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a><span class="co"># ------------------------------</span></span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-7"><a href="#cb57-7" aria-hidden="true" tabindex="-1"></a><span class="co"># ---------- Editable PARAMETERS ----------</span></span>
<span id="cb57-8"><a href="#cb57-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Current pilot estimates (this year) — NOT sufficient</span></span>
<span id="cb57-9"><a href="#cb57-9" aria-hidden="true" tabindex="-1"></a>p_germ_cold_now <span class="ot">&lt;-</span> <span class="fl">0.35</span></span>
<span id="cb57-10"><a href="#cb57-10" aria-hidden="true" tabindex="-1"></a>p_germ_warm_now <span class="ot">&lt;-</span> <span class="fl">0.45</span></span>
<span id="cb57-11"><a href="#cb57-11" aria-hidden="true" tabindex="-1"></a>p_field_survival <span class="ot">&lt;-</span> <span class="fl">0.60</span></span>
<span id="cb57-12"><a href="#cb57-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-13"><a href="#cb57-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Next year (after waiting)</span></span>
<span id="cb57-14"><a href="#cb57-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Warm works well and efficiently</span></span>
<span id="cb57-15"><a href="#cb57-15" aria-hidden="true" tabindex="-1"></a>p_germ_cold_next <span class="ot">&lt;-</span> <span class="fl">0.45</span>   <span class="co"># Cold works but moderately</span></span>
<span id="cb57-16"><a href="#cb57-16" aria-hidden="true" tabindex="-1"></a>p_germ_warm_next <span class="ot">&lt;-</span> <span class="fl">0.65</span>   <span class="co"># Warm works very well next year</span></span>
<span id="cb57-17"><a href="#cb57-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-18"><a href="#cb57-18" aria-hidden="true" tabindex="-1"></a><span class="co"># If you wait one year, you can produce/acquire extra seeds:</span></span>
<span id="cb57-19"><a href="#cb57-19" aria-hidden="true" tabindex="-1"></a>seed_bank_increase_if_wait <span class="ot">&lt;-</span> <span class="dv">4000</span>  </span>
<span id="cb57-20"><a href="#cb57-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-21"><a href="#cb57-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Costs and resources</span></span>
<span id="cb57-22"><a href="#cb57-22" aria-hidden="true" tabindex="-1"></a>cost_per_seed <span class="ot">&lt;-</span> <span class="fl">0.10</span></span>
<span id="cb57-23"><a href="#cb57-23" aria-hidden="true" tabindex="-1"></a>extra_cost_warm_per_seed <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">0.02</span>   <span class="co"># Warm becomes cheaper per seed next year</span></span>
<span id="cb57-24"><a href="#cb57-24" aria-hidden="true" tabindex="-1"></a>fixed_setup_cost <span class="ot">&lt;-</span> <span class="dv">500</span></span>
<span id="cb57-25"><a href="#cb57-25" aria-hidden="true" tabindex="-1"></a>seed_bank_total_now <span class="ot">&lt;-</span> <span class="dv">4000</span>   </span>
<span id="cb57-26"><a href="#cb57-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-27"><a href="#cb57-27" aria-hidden="true" tabindex="-1"></a><span class="co"># Management target</span></span>
<span id="cb57-28"><a href="#cb57-28" aria-hidden="true" tabindex="-1"></a>required_established <span class="ot">&lt;-</span> <span class="dv">3000</span></span>
<span id="cb57-29"><a href="#cb57-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-30"><a href="#cb57-30" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulation settings</span></span>
<span id="cb57-31"><a href="#cb57-31" aria-hidden="true" tabindex="-1"></a>Bsim <span class="ot">&lt;-</span> <span class="dv">2000</span>   <span class="co"># Monte-Carlo replicates for the dramatic distributio</span></span>
<span id="cb57-32"><a href="#cb57-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-33"><a href="#cb57-33" aria-hidden="true" tabindex="-1"></a><span class="co"># ---------- Interactive student inputs ----------</span></span>
<span id="cb57-34"><a href="#cb57-34" aria-hidden="true" tabindex="-1"></a>student_recommendation <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb57-35"><a href="#cb57-35" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">interactive</span>()) {</span>
<span id="cb57-36"><a href="#cb57-36" aria-hidden="true" tabindex="-1"></a>  <span class="cf">repeat</span> {</span>
<span id="cb57-37"><a href="#cb57-37" aria-hidden="true" tabindex="-1"></a>    student_recommendation <span class="ot">&lt;-</span> <span class="fu">readline</span>(<span class="at">prompt =</span> <span class="st">"Choose action for Year 1: type 'Rewild' to rewild now or 'Wait' to delay one year: "</span>)</span>
<span id="cb57-38"><a href="#cb57-38" aria-hidden="true" tabindex="-1"></a>    student_recommendation <span class="ot">&lt;-</span> <span class="fu">trimws</span>(<span class="fu">tolower</span>(student_recommendation))</span>
<span id="cb57-39"><a href="#cb57-39" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (student_recommendation <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"rewild"</span>, <span class="st">"wait"</span>)) <span class="cf">break</span></span>
<span id="cb57-40"><a href="#cb57-40" aria-hidden="true" tabindex="-1"></a>    <span class="fu">cat</span>(<span class="st">"Please type 'Rewild' or 'Wait'.</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb57-41"><a href="#cb57-41" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb57-42"><a href="#cb57-42" aria-hidden="true" tabindex="-1"></a>  student_recommendation <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(student_recommendation <span class="sc">==</span> <span class="st">"rewild"</span>, <span class="st">"Rewild"</span>, <span class="st">"Wait"</span>)</span>
<span id="cb57-43"><a href="#cb57-43" aria-hidden="true" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb57-44"><a href="#cb57-44" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Default for non-interactive runs — change if you knit</span></span>
<span id="cb57-45"><a href="#cb57-45" aria-hidden="true" tabindex="-1"></a>  student_recommendation <span class="ot">&lt;-</span> <span class="st">"Wait"</span>  <span class="co"># "Rewild" or "Wait"</span></span>
<span id="cb57-46"><a href="#cb57-46" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb57-47"><a href="#cb57-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-48"><a href="#cb57-48" aria-hidden="true" tabindex="-1"></a><span class="co"># If rewild now, ask which treatment now</span></span>
<span id="cb57-49"><a href="#cb57-49" aria-hidden="true" tabindex="-1"></a>student_treatment_now <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb57-50"><a href="#cb57-50" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (student_recommendation <span class="sc">==</span> <span class="st">"Rewild"</span>) {</span>
<span id="cb57-51"><a href="#cb57-51" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">interactive</span>()) {</span>
<span id="cb57-52"><a href="#cb57-52" aria-hidden="true" tabindex="-1"></a>    <span class="cf">repeat</span> {</span>
<span id="cb57-53"><a href="#cb57-53" aria-hidden="true" tabindex="-1"></a>      student_treatment_now <span class="ot">&lt;-</span> <span class="fu">readline</span>(<span class="at">prompt =</span> <span class="st">"If rewilding now, choose treatment 'Cold' or 'Warm': "</span>)</span>
<span id="cb57-54"><a href="#cb57-54" aria-hidden="true" tabindex="-1"></a>      student_treatment_now <span class="ot">&lt;-</span> <span class="fu">trimws</span>(<span class="fu">tolower</span>(student_treatment_now))</span>
<span id="cb57-55"><a href="#cb57-55" aria-hidden="true" tabindex="-1"></a>      <span class="cf">if</span> (student_treatment_now <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"cold"</span>, <span class="st">"warm"</span>)) <span class="cf">break</span></span>
<span id="cb57-56"><a href="#cb57-56" aria-hidden="true" tabindex="-1"></a>      <span class="fu">cat</span>(<span class="st">"Please type 'Cold' or 'Warm'.</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb57-57"><a href="#cb57-57" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb57-58"><a href="#cb57-58" aria-hidden="true" tabindex="-1"></a>    student_treatment_now <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(student_treatment_now <span class="sc">==</span> <span class="st">"cold"</span>, <span class="st">"Cold"</span>, <span class="st">"Warm"</span>)</span>
<span id="cb57-59"><a href="#cb57-59" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> {</span>
<span id="cb57-60"><a href="#cb57-60" aria-hidden="true" tabindex="-1"></a>    student_treatment_now <span class="ot">&lt;-</span> <span class="st">"Warm"</span>  <span class="co"># default when not interactive</span></span>
<span id="cb57-61"><a href="#cb57-61" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb57-62"><a href="#cb57-62" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb57-63"><a href="#cb57-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-64"><a href="#cb57-64" aria-hidden="true" tabindex="-1"></a><span class="co"># If wait, ask which treatment they'd plan next year</span></span>
<span id="cb57-65"><a href="#cb57-65" aria-hidden="true" tabindex="-1"></a>student_treatment_next <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb57-66"><a href="#cb57-66" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (student_recommendation <span class="sc">==</span> <span class="st">"Wait"</span>) {</span>
<span id="cb57-67"><a href="#cb57-67" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">interactive</span>()) {</span>
<span id="cb57-68"><a href="#cb57-68" aria-hidden="true" tabindex="-1"></a>    <span class="cf">repeat</span> {</span>
<span id="cb57-69"><a href="#cb57-69" aria-hidden="true" tabindex="-1"></a>      student_treatment_next <span class="ot">&lt;-</span> <span class="fu">readline</span>(<span class="at">prompt =</span> <span class="st">"If waiting, which treatment will you use next year? Type 'Cold' or 'Warm': "</span>)</span>
<span id="cb57-70"><a href="#cb57-70" aria-hidden="true" tabindex="-1"></a>      student_treatment_next <span class="ot">&lt;-</span> <span class="fu">trimws</span>(<span class="fu">tolower</span>(student_treatment_next))</span>
<span id="cb57-71"><a href="#cb57-71" aria-hidden="true" tabindex="-1"></a>      <span class="cf">if</span> (student_treatment_next <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"cold"</span>, <span class="st">"warm"</span>)) <span class="cf">break</span></span>
<span id="cb57-72"><a href="#cb57-72" aria-hidden="true" tabindex="-1"></a>      <span class="fu">cat</span>(<span class="st">"Please type 'Cold' or 'Warm'.</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb57-73"><a href="#cb57-73" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb57-74"><a href="#cb57-74" aria-hidden="true" tabindex="-1"></a>    student_treatment_next <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(student_treatment_next <span class="sc">==</span> <span class="st">"cold"</span>, <span class="st">"Cold"</span>, <span class="st">"Warm"</span>)</span>
<span id="cb57-75"><a href="#cb57-75" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> {</span>
<span id="cb57-76"><a href="#cb57-76" aria-hidden="true" tabindex="-1"></a>    student_treatment_next <span class="ot">&lt;-</span> <span class="st">"Warm"</span>  <span class="co"># default when not interactive</span></span>
<span id="cb57-77"><a href="#cb57-77" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb57-78"><a href="#cb57-78" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb57-79"><a href="#cb57-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-80"><a href="#cb57-80" aria-hidden="true" tabindex="-1"></a><span class="co"># ---------- Helper function to evaluate a plan ----------</span></span>
<span id="cb57-81"><a href="#cb57-81" aria-hidden="true" tabindex="-1"></a><span class="co"># plan: list with elements: when = 0 (now) or 1 (wait 1 year), treatment 'Cold'/'Warm'</span></span>
<span id="cb57-82"><a href="#cb57-82" aria-hidden="true" tabindex="-1"></a>evaluate_plan <span class="ot">&lt;-</span> <span class="cf">function</span>(plan, <span class="at">seed_bank_now =</span> seed_bank_total_now, <span class="at">verbose =</span> <span class="cn">FALSE</span>) {</span>
<span id="cb57-83"><a href="#cb57-83" aria-hidden="true" tabindex="-1"></a>  <span class="co"># choose p_germ depending on plan timing and treatment</span></span>
<span id="cb57-84"><a href="#cb57-84" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (plan<span class="sc">$</span>when <span class="sc">==</span> <span class="dv">0</span>) {</span>
<span id="cb57-85"><a href="#cb57-85" aria-hidden="true" tabindex="-1"></a>    p_germ_plan <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(plan<span class="sc">$</span>treatment <span class="sc">==</span> <span class="st">"Cold"</span>, p_germ_cold_now, p_germ_warm_now)</span>
<span id="cb57-86"><a href="#cb57-86" aria-hidden="true" tabindex="-1"></a>    effective_seed_bank <span class="ot">&lt;-</span> seed_bank_now</span>
<span id="cb57-87"><a href="#cb57-87" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> { <span class="co"># waiting one year: use next-year explicit probabilities and increased seeds</span></span>
<span id="cb57-88"><a href="#cb57-88" aria-hidden="true" tabindex="-1"></a>    p_germ_plan <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(plan<span class="sc">$</span>treatment <span class="sc">==</span> <span class="st">"Cold"</span>, p_germ_cold_next, p_germ_warm_next)</span>
<span id="cb57-89"><a href="#cb57-89" aria-hidden="true" tabindex="-1"></a>    effective_seed_bank <span class="ot">&lt;-</span> seed_bank_now <span class="sc">+</span> seed_bank_increase_if_wait</span>
<span id="cb57-90"><a href="#cb57-90" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb57-91"><a href="#cb57-91" aria-hidden="true" tabindex="-1"></a>  p_germ_plan <span class="ot">&lt;-</span> <span class="fu">max</span>(p_germ_plan, <span class="dv">0</span>)  <span class="co"># safety</span></span>
<span id="cb57-92"><a href="#cb57-92" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb57-93"><a href="#cb57-93" aria-hidden="true" tabindex="-1"></a>  <span class="co"># cost per seed for plan</span></span>
<span id="cb57-94"><a href="#cb57-94" aria-hidden="true" tabindex="-1"></a>  extra_cost_per_seed <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(plan<span class="sc">$</span>treatment <span class="sc">==</span> <span class="st">"Cold"</span>, <span class="dv">0</span>, extra_cost_warm_per_seed)</span>
<span id="cb57-95"><a href="#cb57-95" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb57-96"><a href="#cb57-96" aria-hidden="true" tabindex="-1"></a>  <span class="co"># combined establishment probability</span></span>
<span id="cb57-97"><a href="#cb57-97" aria-hidden="true" tabindex="-1"></a>  p_establish <span class="ot">&lt;-</span> p_germ_plan <span class="sc">*</span> p_field_survival</span>
<span id="cb57-98"><a href="#cb57-98" aria-hidden="true" tabindex="-1"></a>  <span class="co"># seeds needed in expectation (ceiling)</span></span>
<span id="cb57-99"><a href="#cb57-99" aria-hidden="true" tabindex="-1"></a>  seeds_needed <span class="ot">&lt;-</span> <span class="cf">if</span> (p_establish <span class="sc">&gt;</span> <span class="dv">0</span>) <span class="fu">ceiling</span>(required_established <span class="sc">/</span> p_establish) <span class="cf">else</span> <span class="cn">Inf</span></span>
<span id="cb57-100"><a href="#cb57-100" aria-hidden="true" tabindex="-1"></a>  <span class="co"># total cost</span></span>
<span id="cb57-101"><a href="#cb57-101" aria-hidden="true" tabindex="-1"></a>  total_cost <span class="ot">&lt;-</span> seeds_needed <span class="sc">*</span> (cost_per_seed <span class="sc">+</span> extra_cost_per_seed) <span class="sc">+</span> fixed_setup_cost</span>
<span id="cb57-102"><a href="#cb57-102" aria-hidden="true" tabindex="-1"></a>  <span class="co"># seed bank sufficiency</span></span>
<span id="cb57-103"><a href="#cb57-103" aria-hidden="true" tabindex="-1"></a>  suff <span class="ot">&lt;-</span> seeds_needed <span class="sc">&lt;=</span> effective_seed_bank</span>
<span id="cb57-104"><a href="#cb57-104" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb57-105"><a href="#cb57-105" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Monte Carlo simulate established plants (simulate seeds_needed seeds)</span></span>
<span id="cb57-106"><a href="#cb57-106" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set.seed</span>(<span class="dv">100</span> <span class="sc">+</span> plan<span class="sc">$</span>when <span class="sc">+</span> <span class="fu">nchar</span>(plan<span class="sc">$</span>treatment)) <span class="co"># reproducible-ish</span></span>
<span id="cb57-107"><a href="#cb57-107" aria-hidden="true" tabindex="-1"></a>  established <span class="ot">&lt;-</span> <span class="fu">numeric</span>(Bsim)</span>
<span id="cb57-108"><a href="#cb57-108" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">is.finite</span>(seeds_needed) <span class="sc">&amp;&amp;</span> seeds_needed <span class="sc">&gt;</span> <span class="dv">0</span> <span class="sc">&amp;&amp;</span> seeds_needed <span class="sc">&lt;</span> <span class="cn">Inf</span>) {</span>
<span id="cb57-109"><a href="#cb57-109" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> (b <span class="cf">in</span> <span class="fu">seq_len</span>(Bsim)) {</span>
<span id="cb57-110"><a href="#cb57-110" aria-hidden="true" tabindex="-1"></a>      germinated <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(<span class="dv">1</span>, <span class="at">size =</span> seeds_needed, <span class="at">prob =</span> p_germ_plan)</span>
<span id="cb57-111"><a href="#cb57-111" aria-hidden="true" tabindex="-1"></a>      est <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(<span class="dv">1</span>, <span class="at">size =</span> germinated, <span class="at">prob =</span> p_field_survival)</span>
<span id="cb57-112"><a href="#cb57-112" aria-hidden="true" tabindex="-1"></a>      established[b] <span class="ot">&lt;-</span> est</span>
<span id="cb57-113"><a href="#cb57-113" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb57-114"><a href="#cb57-114" aria-hidden="true" tabindex="-1"></a>    prob_success <span class="ot">&lt;-</span> <span class="fu">mean</span>(established <span class="sc">&gt;=</span> required_established)</span>
<span id="cb57-115"><a href="#cb57-115" aria-hidden="true" tabindex="-1"></a>    expected_established <span class="ot">&lt;-</span> <span class="fu">mean</span>(established)</span>
<span id="cb57-116"><a href="#cb57-116" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> {</span>
<span id="cb57-117"><a href="#cb57-117" aria-hidden="true" tabindex="-1"></a>    established <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">0</span>, Bsim)</span>
<span id="cb57-118"><a href="#cb57-118" aria-hidden="true" tabindex="-1"></a>    prob_success <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb57-119"><a href="#cb57-119" aria-hidden="true" tabindex="-1"></a>    expected_established <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb57-120"><a href="#cb57-120" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb57-121"><a href="#cb57-121" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb57-122"><a href="#cb57-122" aria-hidden="true" tabindex="-1"></a>  <span class="fu">list</span>(</span>
<span id="cb57-123"><a href="#cb57-123" aria-hidden="true" tabindex="-1"></a>    <span class="at">plan =</span> plan,</span>
<span id="cb57-124"><a href="#cb57-124" aria-hidden="true" tabindex="-1"></a>    <span class="at">p_germ_plan =</span> p_germ_plan,</span>
<span id="cb57-125"><a href="#cb57-125" aria-hidden="true" tabindex="-1"></a>    <span class="at">p_establish =</span> p_establish,</span>
<span id="cb57-126"><a href="#cb57-126" aria-hidden="true" tabindex="-1"></a>    <span class="at">seeds_needed =</span> seeds_needed,</span>
<span id="cb57-127"><a href="#cb57-127" aria-hidden="true" tabindex="-1"></a>    <span class="at">effective_seed_bank =</span> effective_seed_bank,</span>
<span id="cb57-128"><a href="#cb57-128" aria-hidden="true" tabindex="-1"></a>    <span class="at">total_cost =</span> total_cost,</span>
<span id="cb57-129"><a href="#cb57-129" aria-hidden="true" tabindex="-1"></a>    <span class="at">suff =</span> suff,</span>
<span id="cb57-130"><a href="#cb57-130" aria-hidden="true" tabindex="-1"></a>    <span class="at">established =</span> established,</span>
<span id="cb57-131"><a href="#cb57-131" aria-hidden="true" tabindex="-1"></a>    <span class="at">prob_success =</span> prob_success,</span>
<span id="cb57-132"><a href="#cb57-132" aria-hidden="true" tabindex="-1"></a>    <span class="at">expected_established =</span> expected_established</span>
<span id="cb57-133"><a href="#cb57-133" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb57-134"><a href="#cb57-134" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb57-135"><a href="#cb57-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-136"><a href="#cb57-136" aria-hidden="true" tabindex="-1"></a><span class="co"># ---------- Build chosen plan depending on student input ----------</span></span>
<span id="cb57-137"><a href="#cb57-137" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (student_recommendation <span class="sc">==</span> <span class="st">"Rewild"</span>) {</span>
<span id="cb57-138"><a href="#cb57-138" aria-hidden="true" tabindex="-1"></a>  chosen_spec <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="at">when =</span> <span class="dv">0</span>, <span class="at">treatment =</span> student_treatment_now)</span>
<span id="cb57-139"><a href="#cb57-139" aria-hidden="true" tabindex="-1"></a>  chosen_eval <span class="ot">&lt;-</span> <span class="fu">evaluate_plan</span>(chosen_spec)</span>
<span id="cb57-140"><a href="#cb57-140" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Alternative: compare to waiting alternatives (both Cold and Warm next year)</span></span>
<span id="cb57-141"><a href="#cb57-141" aria-hidden="true" tabindex="-1"></a>  alt_wait_cold <span class="ot">&lt;-</span> <span class="fu">evaluate_plan</span>(<span class="fu">list</span>(<span class="at">when =</span> <span class="dv">1</span>, <span class="at">treatment =</span> <span class="st">"Cold"</span>))</span>
<span id="cb57-142"><a href="#cb57-142" aria-hidden="true" tabindex="-1"></a>  alt_wait_warm <span class="ot">&lt;-</span> <span class="fu">evaluate_plan</span>(<span class="fu">list</span>(<span class="at">when =</span> <span class="dv">1</span>, <span class="at">treatment =</span> <span class="st">"Warm"</span>))</span>
<span id="cb57-143"><a href="#cb57-143" aria-hidden="true" tabindex="-1"></a>  <span class="co"># best alternative is the wait option with higher prob_success</span></span>
<span id="cb57-144"><a href="#cb57-144" aria-hidden="true" tabindex="-1"></a>  alternative_plan <span class="ot">&lt;-</span> <span class="cf">if</span> (alt_wait_cold<span class="sc">$</span>prob_success <span class="sc">&gt;=</span> alt_wait_warm<span class="sc">$</span>prob_success) alt_wait_cold <span class="cf">else</span> alt_wait_warm</span>
<span id="cb57-145"><a href="#cb57-145" aria-hidden="true" tabindex="-1"></a>} <span class="cf">else</span> { <span class="co"># student chose Wait</span></span>
<span id="cb57-146"><a href="#cb57-146" aria-hidden="true" tabindex="-1"></a>  <span class="co"># chosen plan is wait + student_treatment_next</span></span>
<span id="cb57-147"><a href="#cb57-147" aria-hidden="true" tabindex="-1"></a>  chosen_eval <span class="ot">&lt;-</span> <span class="fu">evaluate_plan</span>(<span class="fu">list</span>(<span class="at">when =</span> <span class="dv">1</span>, <span class="at">treatment =</span> student_treatment_next))</span>
<span id="cb57-148"><a href="#cb57-148" aria-hidden="true" tabindex="-1"></a>  <span class="co"># alternative: best immediate rewild now (choose best of Cold/Warm now)</span></span>
<span id="cb57-149"><a href="#cb57-149" aria-hidden="true" tabindex="-1"></a>  alt_now_cold <span class="ot">&lt;-</span> <span class="fu">evaluate_plan</span>(<span class="fu">list</span>(<span class="at">when =</span> <span class="dv">0</span>, <span class="at">treatment =</span> <span class="st">"Cold"</span>))</span>
<span id="cb57-150"><a href="#cb57-150" aria-hidden="true" tabindex="-1"></a>  alt_now_warm <span class="ot">&lt;-</span> <span class="fu">evaluate_plan</span>(<span class="fu">list</span>(<span class="at">when =</span> <span class="dv">0</span>, <span class="at">treatment =</span> <span class="st">"Warm"</span>))</span>
<span id="cb57-151"><a href="#cb57-151" aria-hidden="true" tabindex="-1"></a>  alternative_plan <span class="ot">&lt;-</span> <span class="cf">if</span> (alt_now_cold<span class="sc">$</span>prob_success <span class="sc">&gt;=</span> alt_now_warm<span class="sc">$</span>prob_success) alt_now_cold <span class="cf">else</span> alt_now_warm</span>
<span id="cb57-152"><a href="#cb57-152" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb57-153"><a href="#cb57-153" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-154"><a href="#cb57-154" aria-hidden="true" tabindex="-1"></a>chosen_plan <span class="ot">&lt;-</span> chosen_eval</span>
<span id="cb57-155"><a href="#cb57-155" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-156"><a href="#cb57-156" aria-hidden="true" tabindex="-1"></a><span class="co"># ---------- Decide "right decision" with feasibility rule ----------</span></span>
<span id="cb57-157"><a href="#cb57-157" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-158"><a href="#cb57-158" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span>chosen_plan<span class="sc">$</span>suff) {</span>
<span id="cb57-159"><a href="#cb57-159" aria-hidden="true" tabindex="-1"></a>  <span class="co"># If seed bank is insufficient, automatically not optimal</span></span>
<span id="cb57-160"><a href="#cb57-160" aria-hidden="true" tabindex="-1"></a>  right_decision <span class="ot">&lt;-</span> <span class="cn">FALSE</span></span>
<span id="cb57-161"><a href="#cb57-161" aria-hidden="true" tabindex="-1"></a>} <span class="cf">else</span> <span class="cf">if</span> (<span class="sc">!</span>alternative_plan<span class="sc">$</span>suff) {</span>
<span id="cb57-162"><a href="#cb57-162" aria-hidden="true" tabindex="-1"></a>  <span class="co"># If alternative is infeasible but chosen plan is feasible</span></span>
<span id="cb57-163"><a href="#cb57-163" aria-hidden="true" tabindex="-1"></a>  right_decision <span class="ot">&lt;-</span> <span class="cn">TRUE</span></span>
<span id="cb57-164"><a href="#cb57-164" aria-hidden="true" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb57-165"><a href="#cb57-165" aria-hidden="true" tabindex="-1"></a>  <span class="co"># If both feasible, compare probability of success</span></span>
<span id="cb57-166"><a href="#cb57-166" aria-hidden="true" tabindex="-1"></a>  right_decision <span class="ot">&lt;-</span> chosen_plan<span class="sc">$</span>prob_success <span class="sc">&gt;=</span> alternative_plan<span class="sc">$</span>prob_success</span>
<span id="cb57-167"><a href="#cb57-167" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb57-168"><a href="#cb57-168" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-169"><a href="#cb57-169" aria-hidden="true" tabindex="-1"></a><span class="co"># ---------- Plot distribution for the chosen plan ----------</span></span>
<span id="cb57-170"><a href="#cb57-170" aria-hidden="true" tabindex="-1"></a>df_plot <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">established =</span> chosen_plan<span class="sc">$</span>established)</span>
<span id="cb57-171"><a href="#cb57-171" aria-hidden="true" tabindex="-1"></a>fill_col <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(chosen_plan<span class="sc">$</span>plan<span class="sc">$</span>treatment <span class="sc">==</span> <span class="st">"Cold"</span>, <span class="st">"#2C7BB6"</span>, <span class="st">"#D7191C"</span>)</span>
<span id="cb57-172"><a href="#cb57-172" aria-hidden="true" tabindex="-1"></a>border_col <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(right_decision, <span class="st">"#2E7D32"</span>, <span class="st">"#B00020"</span>) <span class="co"># green border for correct, red for wrong</span></span>
<span id="cb57-173"><a href="#cb57-173" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-174"><a href="#cb57-174" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(df_plot, <span class="fu">aes</span>(<span class="at">x =</span> established)) <span class="sc">+</span></span>
<span id="cb57-175"><a href="#cb57-175" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">50</span>, <span class="at">fill =</span> fill_col, <span class="at">colour =</span> <span class="st">"black"</span>, <span class="at">alpha =</span> <span class="fl">0.85</span>) <span class="sc">+</span></span>
<span id="cb57-176"><a href="#cb57-176" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> required_established, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">size =</span> <span class="fl">1.1</span>) <span class="sc">+</span></span>
<span id="cb57-177"><a href="#cb57-177" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="fu">paste0</span>(<span class="st">"Outcome distribution for your chosen plan: "</span>,</span>
<span id="cb57-178"><a href="#cb57-178" aria-hidden="true" tabindex="-1"></a>                      <span class="fu">ifelse</span>(chosen_plan<span class="sc">$</span>plan<span class="sc">$</span>when<span class="sc">==</span><span class="dv">0</span>, <span class="st">"Rewild now"</span>, <span class="st">"Wait 1 year then rewild"</span>),</span>
<span id="cb57-179"><a href="#cb57-179" aria-hidden="true" tabindex="-1"></a>                      <span class="st">" ("</span>, chosen_plan<span class="sc">$</span>plan<span class="sc">$</span>treatment, <span class="st">")"</span>),</span>
<span id="cb57-180"><a href="#cb57-180" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="fu">paste0</span>(<span class="st">"p_germ used = "</span>, <span class="fu">round</span>(chosen_plan<span class="sc">$</span>p_germ_plan,<span class="dv">3</span>),</span>
<span id="cb57-181"><a href="#cb57-181" aria-hidden="true" tabindex="-1"></a>                         <span class="st">" ; p_field = "</span>, p_field_survival,</span>
<span id="cb57-182"><a href="#cb57-182" aria-hidden="true" tabindex="-1"></a>                         <span class="st">" ; prob success = "</span>, <span class="fu">round</span>(chosen_plan<span class="sc">$</span>prob_success,<span class="dv">3</span>)),</span>
<span id="cb57-183"><a href="#cb57-183" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Number of established plants"</span>, <span class="at">y =</span> <span class="st">"Simulated replicates"</span>) <span class="sc">+</span></span>
<span id="cb57-184"><a href="#cb57-184" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">13</span>) <span class="sc">+</span></span>
<span id="cb57-185"><a href="#cb57-185" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">panel.border =</span> <span class="fu">element_rect</span>(<span class="at">colour =</span> border_col, <span class="at">fill =</span> <span class="cn">NA</span>, <span class="at">size =</span> <span class="dv">2</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
ℹ Please use `linewidth` instead.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: The `size` argument of `element_rect()` is deprecated as of ggplot2 3.4.0.
ℹ Please use the `linewidth` argument instead.</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(p)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Rewild-or-Wait---analysing-proportions_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ---------- Dramatic summary ----------</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">================= Decision Simulator Summary =================</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
================= Decision Simulator Summary =================</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Your initial choice (Rewild now / Wait):"</span>, student_recommendation, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Your initial choice (Rewild now / Wait): Wait </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (student_recommendation <span class="sc">==</span> <span class="st">"Rewild"</span>) {</span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"You chose to rewild now with treatment:"</span>, chosen_plan<span class="sc">$</span>plan<span class="sc">$</span>treatment, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"You chose to wait and will use treatment next year:"</span>, chosen_plan<span class="sc">$</span>plan<span class="sc">$</span>treatment, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>You chose to wait and will use treatment next year: Warm </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">-- Chosen plan estimates --</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
-- Chosen plan estimates --</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Assumed germination used for plan:"</span>, <span class="fu">round</span>(chosen_plan<span class="sc">$</span>p_germ_plan,<span class="dv">3</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Assumed germination used for plan: 0.65 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Combined per-seed establishment prob:"</span>, <span class="fu">round</span>(chosen_plan<span class="sc">$</span>p_establish,<span class="dv">4</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Combined per-seed establishment prob: 0.39 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Seeds required (expected):"</span>, chosen_plan<span class="sc">$</span>seeds_needed, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Seeds required (expected): 7693 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Effective seed bank available for this plan:"</span>, chosen_plan<span class="sc">$</span>effective_seed_bank, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Effective seed bank available for this plan: 8000 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span>chosen_plan<span class="sc">$</span>suff) {</span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"!!! Seed bank INSUFFICIENT by"</span>, chosen_plan<span class="sc">$</span>seeds_needed <span class="sc">-</span> chosen_plan<span class="sc">$</span>effective_seed_bank, <span class="st">"seeds</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb77-4"><a href="#cb77-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"Seed bank sufficient. Seeds remaining if used:"</span>, chosen_plan<span class="sc">$</span>effective_seed_bank <span class="sc">-</span> chosen_plan<span class="sc">$</span>seeds_needed, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb77-5"><a href="#cb77-5" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Seed bank sufficient. Seeds remaining if used: 307 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Estimated total cost: $"</span>, <span class="fu">round</span>(chosen_plan<span class="sc">$</span>total_cost,<span class="dv">2</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Estimated total cost: $ 1115.44 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Monte Carlo probability of meeting target (&gt;= "</span>, required_established, <span class="st">"): "</span>, <span class="fu">round</span>(chosen_plan<span class="sc">$</span>prob_success<span class="sc">*</span><span class="dv">100</span>,<span class="dv">1</span>), <span class="st">"%</span><span class="sc">\n</span><span class="st">"</span>, <span class="at">sep =</span> <span class="st">""</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Monte Carlo probability of meeting target (&gt;= 3000): 50.1%</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">-- Alternative plan (what you'd have gotten otherwise) --</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
-- Alternative plan (what you'd have gotten otherwise) --</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Alternative chosen (best alternative): Wait ="</span>, alternative_plan<span class="sc">$</span>plan<span class="sc">$</span>when<span class="sc">==</span><span class="dv">1</span>, <span class="st">"; treatment ="</span>, alternative_plan<span class="sc">$</span>plan<span class="sc">$</span>treatment, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Alternative chosen (best alternative): Wait = FALSE ; treatment = Warm </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Assumed germination (alternative):"</span>, <span class="fu">round</span>(alternative_plan<span class="sc">$</span>p_germ_plan,<span class="dv">3</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Assumed germination (alternative): 0.45 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Effective seed bank for alternative:"</span>, alternative_plan<span class="sc">$</span>effective_seed_bank, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Effective seed bank for alternative: 4000 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Probability of meeting target under alternative:"</span>, <span class="fu">round</span>(alternative_plan<span class="sc">$</span>prob_success<span class="sc">*</span><span class="dv">100</span>,<span class="dv">1</span>), <span class="st">"%</span><span class="sc">\n</span><span class="st">"</span>, <span class="at">sep =</span> <span class="st">""</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Probability of meeting target under alternative:50.4%</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">VERDICT: "</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
VERDICT: </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span>chosen_plan<span class="sc">$</span>suff) {</span>
<span id="cb95-2"><a href="#cb95-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"NOT optimal — insufficient seeds to implement this plan.</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb95-3"><a href="#cb95-3" aria-hidden="true" tabindex="-1"></a>} <span class="cf">else</span> <span class="cf">if</span> (right_decision) {</span>
<span id="cb95-4"><a href="#cb95-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"RIGHT (better than the alternative under current assumptions).</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb95-5"><a href="#cb95-5" aria-hidden="true" tabindex="-1"></a>} <span class="cf">else</span> {</span>
<span id="cb95-6"><a href="#cb95-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"NOT optimal (the alternative had higher probability of success).</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb95-7"><a href="#cb95-7" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>RIGHT (better than the alternative under current assumptions).</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"===============================================================</span><span class="sc">\n\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>===============================================================</code></pre>
</div>
</div>
</section>
<section id="extra---experimental-designing" class="level1">
<h1>10. Extra - experimental designing</h1>
<p>Edit the numbers and check how you would interpret a different scenarios. You could even include economical estimates for the different treatments. In this practical I propsed a debate/borderline scenario, where the difference between treatments was very close to the practical threshold. You could also test a clear-win scenario, where Cold true p ≈ 0.40 and Warm true p ≈ 0.60; or a mild improvement case with Cold true p ≈ 0.40 and Warm true p ≈ 0.45. To change this look for these lines:</p>
<p>df$n_germinated &lt;- c(rbinom(12, size = 25, prob = 0.40), rbinom(12, size = 25, prob = 0.50))</p>
<p>And change the 0.40 for any other probability you want for the cold treatment, and the 0.50 for any other number for the warm treatment.</p>
<p>Feel free to change also the number of seeds we planted on each petri dish (25) or the number of petri dishes we used (replicates number, 12). In this case you will also need to change this line with the appropiate numbers.</p>
<p>df &lt;- data.frame(tray = 1:24, treatment = rep(c(“Cold”,“Warm”), each = 12), n_seeds = rep(25, 24) )</p>
<p><strong>FINAL NOTE:</strong> Statistics does not tell us what to do. It tells us <strong>how uncertain</strong> we are when we decide.</p>
<p><sub><strong>Possible&nbsp;answer</strong>:&nbsp;Changing&nbsp;the&nbsp;probabilities,&nbsp;number&nbsp;of&nbsp;replicates,&nbsp;or&nbsp;seeds&nbsp;per&nbsp;Petri&nbsp;dish&nbsp;clearly&nbsp;shows&nbsp;how&nbsp;strongly&nbsp;sample&nbsp;size&nbsp;influences&nbsp;our&nbsp;conclusions.&nbsp;When&nbsp;we&nbsp;increase&nbsp;the&nbsp;number&nbsp;of&nbsp;seeds&nbsp;or&nbsp;replicates,&nbsp;confidence&nbsp;intervals&nbsp;become&nbsp;narrower&nbsp;and&nbsp;p-values&nbsp;more&nbsp;stable,&nbsp;meaning&nbsp;we&nbsp;can&nbsp;estimate&nbsp;germination&nbsp;rates&nbsp;with&nbsp;greater&nbsp;precision.&nbsp;With&nbsp;only&nbsp;10&nbsp;seeds&nbsp;per&nbsp;dish,&nbsp;random&nbsp;variation&nbsp;is&nbsp;much&nbsp;larger,&nbsp;one&nbsp;or&nbsp;two&nbsp;seeds&nbsp;can&nbsp;change&nbsp;the&nbsp;proportion&nbsp;dramatically,&nbsp;making&nbsp;it&nbsp;harder&nbsp;to&nbsp;detect&nbsp;real&nbsp;differences&nbsp;between&nbsp;treatments.&nbsp;In&nbsp;contrast,&nbsp;100&nbsp;seeds&nbsp;per&nbsp;dish&nbsp;greatly&nbsp;reduces&nbsp;uncertainty,&nbsp;because&nbsp;each&nbsp;individual&nbsp;seed&nbsp;has&nbsp;less&nbsp;influence&nbsp;on&nbsp;the&nbsp;final&nbsp;proportion.&nbsp;However,&nbsp;this&nbsp;decision&nbsp;clearly&nbsp;impacts&nbsp;the&nbsp;lab&nbsp;work&nbsp;and&nbsp;cost&nbsp;of&nbsp;the&nbsp;experiment.&nbsp;Whether&nbsp;10&nbsp;seeds&nbsp;are&nbsp;“enough”&nbsp;depends&nbsp;on&nbsp;the&nbsp;expected&nbsp;germination&nbsp;proportion&nbsp;and&nbsp;the&nbsp;size&nbsp;of&nbsp;the&nbsp;effect&nbsp;we&nbsp;want&nbsp;to&nbsp;detect.&nbsp;If&nbsp;germination&nbsp;is&nbsp;very&nbsp;high&nbsp;(e.g.&nbsp;80–90%)&nbsp;or&nbsp;very&nbsp;low&nbsp;(e.g.&nbsp;5–10%),&nbsp;even&nbsp;small&nbsp;samples&nbsp;might&nbsp;show&nbsp;clear&nbsp;differences.&nbsp;However,&nbsp;when&nbsp;proportions&nbsp;are&nbsp;around&nbsp;40–60%,&nbsp;as&nbsp;in&nbsp;our&nbsp;case,&nbsp;variability&nbsp;is&nbsp;highest,&nbsp;so&nbsp;larger&nbsp;sample&nbsp;sizes&nbsp;are&nbsp;needed&nbsp;to&nbsp;confidently&nbsp;detect&nbsp;moderate&nbsp;differences&nbsp;(e.g.&nbsp;10%).&nbsp;Therefore,&nbsp;experimental&nbsp;design&nbsp;should&nbsp;always&nbsp;consider&nbsp;the&nbsp;expected&nbsp;proportion&nbsp;and&nbsp;the&nbsp;minimum&nbsp;biologically&nbsp;meaningful&nbsp;difference&nbsp;before&nbsp;deciding&nbsp;how&nbsp;many&nbsp;seeds&nbsp;or&nbsp;replicates&nbsp;to&nbsp;use.&nbsp;The&nbsp;number&nbsp;of&nbsp;seeds&nbsp;per&nbsp;dish&nbsp;and&nbsp;the&nbsp;number&nbsp;of&nbsp;replicates&nbsp;directly&nbsp;control&nbsp;statistical&nbsp;precision.&nbsp;Good&nbsp;experimental&nbsp;design&nbsp;is&nbsp;not&nbsp;about&nbsp;using&nbsp;as&nbsp;many&nbsp;seeds&nbsp;as&nbsp;possible&nbsp;—&nbsp;it&nbsp;is&nbsp;about&nbsp;using&nbsp;enough&nbsp;to&nbsp;detect&nbsp;the&nbsp;effect&nbsp;size&nbsp;that&nbsp;matters&nbsp;biologically.</sub></p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>